### ISSUE TITLE
Chapter1. 자바 8, 9, 10, 11 ~ Chapter2. 동작 파라미터화 코드 전달하기

### ISSUE THREAD

**Issue by tmfrl1552** [FireInStove/modern-java-in-action#1]
## 👑 스터디장
인석 (@ aimhigh53)

## 📖 스터디 범위
Chapter1 자바 8, 9, 10, 11 ~ Chapter2 동작 파라미터화 코드 전달하기

## 🕧 스터디 일정
23/11/09 (목) 09시

**Comment by yougahee** [comment]
# 📖 1장. 자바는 무슨일이 일어나고 있는가

## 자바는 아직도 변화한다.
1) 멀티코어 벙렬성
	- 맨 처음에는 스레드를 지원했지만, 멀티코어를 병렬로 쉽게 사용할 수 있도록 스트림API 제공

2) 스트림 API
- 스트림이란? 
	- 한 번에 한 개씩 만들어지는 연속적인 데이터 항목들의 모임

3) 동작 파라미터화
- ex. sort의 동작을 파라미터화했던 것처럼 스트림 API는 연산의 동작을 파라미터화할 수 있는 코드를 전달한다.

4) 메서드 참조
- ex) File::isHidden > :: 가 메서드 참조

# 📖 2장. 동작 파라미터화 코드 전달하기
## 동작 파라미터화
- 아직은 어떻게 실행할 것인지 결정하지 않은 코드 블록을 의미
- 조건식이 필요한 경우, 파라미터로 만들어서 사용하라.(동일한 코드를 반복하는 것은 좋지 않다.)

### Predicate
- 확실히 유연해진 것을 느낄 수 있음.
- 동작을 ApplePredicate 로 만들고, 파라미터에 집어 넣으면 해당 동작을 할 수 있음
- 장점 : 적용할 동작을 따로 분리할 수 있다.

```java
public static List<Apple> filterApples(List<Apple> inventory, ApplePredicate p) {

	var result = new ArrayList<Apple>();
	for(Apple apple : inventory) {
		if(p.test(apple)) {
			result.add(apple);
		}
	}

	return  result
}

```

### 위의 예시를 좀 더 간략하게, 익명클래스
- 지역 클래스와 비슷한 개념이고, 이름이 없는 클래스이다.
- 익명클래스를 이용하면 클래스 선언과 인스턴스화를 동시에 할 수 있다.

```java
	var redApples = filterAppples(inventory, new ApplePredicate() {
		public boolean test(Apple apple) {
			return RED.equals(apple.getColor());
		}
	})
```

- 그러나, 반복되어 지저분한 코드가 있고, 한눈에 이해하기 어렵다.


### 람다 표현식
```java
	List<Apple> result = filterApples(inventory, (Apple apple) -> RED.equals(apple.getColor()))
```

### ExecuterService
- Task 제출과 실행과정의 연관성을 끊어준다. 
- 태스크를 스레드풀로 보내고 결과를 Future로 저장할 수 있다.
- Callable 인터페이스를 이용해 결과를 반환하는 테스크를 만들 수 있다.
``` java
Future<String> threadName = executorService.submit(
() -> Thread.currentThread().getName())

```

**Comment by aimhigh53** [comment]
## ✏️ 1주차 

## 1.1역사의 흐름은 무엇인가?

멀티코어 CPU의 대중화 적인 하드웨어 변화도 자바 8에 영향을 줌
자바 8특징
- 스트림API
- 메서드에 코드를 전달하는 기법
- 인터페이스의 디폴트 메서드


## 1.2 왜 아직도 자바는 변화하는가?
- 특정 분야에서 장점을 가진 언어는 다른 경쟁 언어를 도태시킨다. 단지 새로운 하나의 기능 때문에 기존 언어를 버리고 새로운 언어와 툴 체인으로 바꾼다는 것은 쉽지 않은 일이다. 하지만 새로운 프로그래밍을 배우는 사람은 (기존 언어가 재빠르게 진화하지 않는다면) 자연스럽게 새로운 언어를 선택하게 되며 기존 언어는 도태된다.

## 1.2.1 프로그래밍 언어 생테계에서 자바의 위치
- 등장 당시 각광받던 객체 지향 패러다임에 적합
- 스레드와 락을 이용한 동시성 지원 등 처음부터 많은 유용한 라이브러리를 포함
- 코드를 JVM 바이트코드로 컴파일하는 특징

## 1.2.2 스트림 처리(stream processing)
자바 8에는 스트림 API가 추가됐는데, 스트림 패키지에 정의된 Stream<T>는 T형식으로 구성된 일련의 항목을 의미한다
유닉스 명령어로 복잡한 파이프라인을 구성했던것처럼 스트림 API는 파이프라인을 만드는데 필요한 많은 메서드를 제공함

## 1.2.3 동작 파라미터화로 메서드에 코드 전달하기
    - 자바 8에 추가된 두 번째 프로그램 개념은 코드 일부를 메서드로 전달하는 기능이다. 자바 8에서는 메서드(코드)를 다른 메서드의 인수로 넘겨주는 기능을 제공한다. 이러한 기능을 동작 파라미터화라고 부름

## 1.2.4 병렬성과 공유 가변 데이터
  - 병렬성을 공짜로 얻을 수 있다 보통 다른 코드와 동시에 실행하더라도 안전하게 실행할 수 있는 코드를 만들려면 공유된 가변 데이터에 접근하지 않아야 한다.
 
## 1.2.5 자바가 진화해야 하는 이유
- 제네릭이 나타나고, List가 List<String> 등.. 해서 변화됐고, 가독성 좋아졌다. 함수형 프로그래밍으로 다가서게됨. 함수형을 도입함으로써  두가지 프로그래밍 패러다임의 장점을 모두 활용할 수 있게 됐다.(객체지향, 함수형)
   
- 백그라운드 서비스 모듈
 만약 스프링으로 만든 애플리케이션이 UI를 따로 가질 필요는 없고 서버 내에서 백그라운드 서비스처럼 동작할 필요가 있다면 rar 모듈로 만들어서 배포할 수 있다.


## 1.3.1 ~ 1.3.3
- 자바 8에서는 더 이상 메서드가 이급값이 아닌 일급값. 기존에 객체 참조(new로 객체 참조를 생성함)를 이용해서 객체를 이리저리 주고받았던 것처럼 자바 8에서는 File::isHidden-> File[] hiddenFiles = new File(".").listFiles(File::isHidden);
 을 이용해서 메서드 참조를 만들어 전달할 수 있게 되었다.
- Predicate, filterApples는 Apple::isGreenApple 메서드를 Predicate<Apple>이라는 타입의 파라미터로 받는다. 인수로 값을 받아 true나 false를 반환하는 함수를 predicate라고 한다
- 메소드 전달을 람다로

filterApples(inventory, (Apple a) -> "green".equals(a.getColor()));
filterApples(inventory, (Apple a) -> a.getWeight() > 150);
filterApples(inventory, (Apple a) -> a.getWeight() < 80 || "brown".equals(a.getColor()));

## 1.4 ~ 1.5
- 스트림 API를 이용하면 컬렉션 API는 상당히 다른 방식으로 데이터를 처리할 수 있다. 컬렉션에서는 fore-each 루프를 이용해서 반복 과정을 직접 처리해야했다. (external iteration) 반면, 스트림 API를 이용하면 루프를 신경 쓸 필요가 없이 라이브러리 내부에서 모든 데이터가 처리된다. (internal iteration)
- 스트림 API는 자주 반복되는 패턴으로 주어진 조건에 따라 데이터를 필터링(filtering)하거나, 데이터를 추출(extracting), 데이터를 그룹화(grouping)하는 등의 기능을 제공한다.
- 자바 8에서는 인터페이스를 쉽게 바꿀 수 있도록 디폴트 메서드(default method)를 지원한다. 디폴트 메서드는 특정 프로그램을 구현하는 데 도움을 주는 기능이 아니라 미래에 프로그램이 쉽게 변화할 수 있는 환경을 제공하는 기능


## 2.1
- 녹색사과 필터링

`  public static List<Apple> filterGreenApples(List<Apple> inventory) {
    List<Apple> result = new ArrayList<>();
    for (Apple apple : inventory) {
      if (apple.getColor() == Color.GREEN) {
        result.add(apple);
      }
    }
    return result;
  }
`

- 색을 파라미터 화
`  public static List<Apple> filterApplesByColor(List<Apple> inventory, Color color) {
    List<Apple> result = new ArrayList<>();
    for (Apple apple : inventory) {
      if (apple.getColor() == color) {
        result.add(apple);
      }
    }
    return result;
  }
`
- 가능한 모든 속성으로 필터링
` public static List<Apple> filterApplesByWeight(List<Apple> inventory, Color color, int weight, boolean flag) {
    List<Apple> result = new ArrayList<>();
    for (Apple apple : inventory) {
      if ((flag && apple.getColor().equals(color)) ||
           (!flag && apple.getWeight() > weight)) {
        result.add(apple);
      }
    }
    return result;
  }
`
- 익명 클래스 사용
`List<Apple> redApples = filterApples(inventory, new ApplePredicate() {
  public boolean test(Apple a) {
    return RED.equals(apple.getColor());
  }
});
`
- 람다 표현식 사용
`List<Apple> result = filterApples(inventory, (Apple apple) -> RED.equals(apple.getColor()));
`

- 리스트 형식으로 추상화


public interface predicate<T> {
  boolean test(T t);
}

public static <T> List<T> filter(List<T> list, Predicate<T> p) {
  List<T> result = new ArrayList<>();
  for(T e : list) {
    if(p.test(e)) {
      result.add(e);
    }
  }
  return result;
}

List<Apple> redApples = filter(inventory, (Apple apple) -> RED.equals(apple.getColor()));
List<Apple> evenNumers = filter(numbers, (Integer i) -> i % 2 == 0);

**Comment by kyueun** [comment]
# 1. 자바 8, 9, 10, 11 : 무슨 일이 일어나고 있는가?
자바 8에서 제공하는 기술
- 스트림 API
    - 병렬 연산 지원
    - 고수준 언어로 원하는 동작을 표현, 스트림 라이브러리가 최적의 저수준 실행 방법을 선택
- 메서드에 코드를 전달하는 기법
    - 동작 파라미터화 구현
- 인터페이스의 디폴트 매서드

## 스트림 처리
### 스트림
- 한 번에 한 개씩 만들어지는 연속적인 데이터 항목들의 모임
- 한 프로그램의 출력 스트림은 다른 프로그램의 입력 스트림이 될 수 있음
- 스레드를 사용하지 않으면서도 병렬성을 얻을 수 있음

## 동작 파라미터화로 메서드에 코드 전달하기
### 동작 파라미터화
- 메서드를 다른 메서드의 인수로 넘겨주는 기능

## 병렬성과 공유 가변 데이터
- 스트림 -> 병렬성을 얻을 수 있음
- 안전하게 실행하려면 공유된 가변 데이터에 접근하지 않아야 함
- as-is : `synchronized` 이용, 가변 데이터 보호 -> 일반적으로 시스템 성능에 악영향

## 자바 함수
- 자바의 함수 : 메서드와 같은 의미 + 수학적인 함수처럼 사용

### 메서드 참조
`::` 를 이용해서 준비된 함수를 메서드에 직접 전달
- ```java
    File[]  hiddenFiles = new File(".").listFiles(File::isHidden);
    ```

람다를 포함해 함수도 값으로 취급 가능

필터: 특정 항목을 선택해서 반환

Predicate: 인수로 값을 받아서 true/false를 반환하는 함수

### 스트림
반복 작업
- 외부 반복: 각 요소를 반복하면서 작업 수행 ex. `for-each`
- 내부 반복: 라이브러리 내부에서 모든 데이터가 처리 ex. `stream`

### 디폴트 메서드
- 인터페이스를 쉽게 바꿀 수 있도록 지원
- 디폴트 메서드의 본문은 클래스 구현이 아니라 인터페이스의 일부

이 외에도 null 쉽게 다룰 수 있는 `Optinal` 등 함수형 프로그래밍에서 가져온 아이디어들 존재

# 2. 동작 파라미터화 코드 전달하기
## 동작 파라미터화
아직은 어떻게 실행할 것인지 결정하지 않은 코드 블록
- 코드 블록은 나중에 프로그램에서 호출
- 자주 바뀌는 요구사항에 효과적으로 대응 가능

선택 조건을 결정하는 인터페이스 정의
- 프레디케이트: 어떤 속성에 기초해 boolean 값을 반환하는 함수
- 프레디케이트를 인수로 받아 동작 수행 가능

컬렉션 탐색 로직과 각 항목에 적용할 동작 분리 가능

## 익명 클래스
- 이름이 없는 클래스
- 클래스 선언과 인스턴스화를 동시에 가능

예시
- 이전에 Predicate 클래스를 만들었던 걸 인수로 넘겨주는 시점에 클래스 선언하면서 동작을 직접 파라미터화
- ```java
    interface ApplePredicate {
        boolean test(Apple apple);
    }
    class Test {
        List<Apple> filter(List<Apple> inventory, ApplePredicate p) {...}
        void test() {
            List<Apple> inventory = Arrays.asList(...);
            List<Apple> filtered = filter(inventory, new ApplePredicate() {
                public boolean test(Apple apple) {
                    return RED.equals(apple.getColor());
                }
            });
        }
    }
    ```

## 람다 표현식
위 예시 간단하게 재구현 가능
- ```java
    List<Apple> filtered = filter(inventory, (Apple apple) -> RED.equals(apple.getColor()));
    ```

## Runnable
스레드 이용 시, 익명 클래스가 Runnable 인터페이스를 구현하도록 함 -> 람다로 변경 가능

## Callable
ExecutorService 에 전달
- 태스트는 스레드 풀로 보내고, 결과를 Future로 저장 -> 이것도 람다로 변경 가능

**Comment by tmfrl1552** [comment]
# 🚀 Chapter1. 자바 8, 9, 10, 11 : 무슨 일이 일어나고 있는가?
## 1.1 역사의 흐름은 무엇인가?
* 자바 역사를 통틀어 가장 획기적인 변화가 자바8에 나타남
* 멀티코어 CPU 대중화와 같은 하드웨어적인 변화도 자바 8에 영향을 끼침
* 자바1.0 > 스레드와 락, 메모리 모델까지 지원
	* 자바 5 > 스레드 풀, 병렬 실행 컬렉션 도입
	* 자바 7 > 병렬 실행에 도움을 줄 수 있는 포크/조인 프레임워크 제공
* 자바 8은 '간결한 코드', '멀티 코어 프로세서'의 쉬운 활용이라는 두 가지 요구사항 기반 
* 자바 8 제공 새로운 기술
	* 스트림 API
	* 메서드에 코드를 전달하는 기법
	* 인터페이스의 디폴트 메서드
* 메서드에 코드를 전달(뿐만 아니라 결과를 반환하고 다른 자료구조로 전달할 수도 있음)하는
  자바 8 기법은 *함수형 프로그래밍*에서 위력 발휘

## 1.2 왜 아직도 자바는 변화하는가?
* 생태계를 요약하자면, 새로운 언어가 등장하고 새로운 언어는 변화하는 환경에 빠르게 적응하면서 점점 대중화 됨
* 자바 8은 더 다양한 프로그래밍 도구 그리고 다양한 프로그래밍 문제를 더 빠르고 정확하며 
  쉽게 유지보수할 수 있다는 장점 제공

> 자바8 설계의 밑바탕을 이루는 세 가지 프로그래밍 개념
### 스트림 처리
* 스트림이란?
	* 한 번에 한 개씩 만들어지는 연속적인 데이터 항목들의 모임
	* 어떤 프로그램의 출력 스트림은 다른 프로그램의 입력 스트림이 될 수 있음
* 자바 8에는 java.util.stream 패키지에 스트림 API가 추가되어있음

### 동작 파라미터화로 메서드에 코드 전달하기
* 동작 파라미터화
	* 자바8에서는 메서드를 다른 메서들의 인수로 넘겨주는 기능 제공

### 병렬성과 공유 가변 데이터
* 보통 다른 코드와 동시에 실행하더라도 안전하게 실행할 수 있는 코드를 만들려면
  공유된 가변 데이터에 접근하지 않아야 한다.
  	* 순수 함수, 부작용 없는 함수, 상태 없는 함수
* 다중 프로세싱 코어에서 synchronized를 사용하면 생각보다 훨씬 더 비싼 대가를 치룰 수 있음
	* 다중 처리 코어에서는 코드가 순차적으로 실행되어야 하므로
	  병렬이라는 목적을 무력화 시키면서..
* 함수형 프로그래밍 => 공유되지 않은 가변 데이터, 메서드, 함수 코드를 다른 메서드로 전달하는 두 가지 기능은 핵심적인 사항
* 명령형 프로그래밍 => 일련의 가변 상태로 프로그램 정의


## 1.3 자바 함수
* 프로그래밍 언어에서 함수(function) 용어
	* 메서드 특히 정적 메서드와 같은 의미로 사용
	* 자바의 함수는 '수학적인 함수'처럼 사용되며 부작용을 일으키지 않는 함수 의미

### 람다: 익명 함수
* 자바 8 에서는 메서드를 일급 값으로 취급할 뿐 아니라 람다(또는 익명 함수)를 포함하여 함수도 값으로 취급
* 직접 메서드를 정의할 수도 있지만, 이용할 수 있는 편리한 클래스나 메서드가 없을 때
  새로운 람다 문법을 이용하면 더 간결하게 코드 구현 가능

* 람다 문법 형식으로 구현된 프로그램 > '함수형 프로그래밍' 이라고 함
	* 함수를 일급값으로 넘겨주는 프로그램을 구현한다 라고도 함

#### 메서드 전달에서 람다로
* 한 두번만 사용할 메서드를 매번 정의하는 것은 귀찮은 일
  > 자바8 에서는 람다라는 새로운 개념으로 코드 구현
``` java
filterApples(inventory, (Apple a) -> GREEN.equals(a.getColor()) );
```

* 람다가 몇 줄 이상으로 길어진다면, 익명 람다보다는 
  코드가 수행하는 일을 잘 설명하는 이름을 가진 메서드 정의하고 메서드 참조를 활용하는 것이 바람직
  * 코드의 명확성이 우선시 돼야 함.

<br>

## 1.4 스트림
* 외부 반복
	* for-each 루프를 이용해서 각 요소를 반복하면서 작업 수행
* 내부 반복
	* stream API 처럼 라이브러리 내부에서 모든 데이터가 처리
* 멀티 코어 컴퓨터
	* 전통적인 자바 프로그램은 많은 CPU 중 단 하나만 사용하면서 나머지 CPU 낭비 시키는게 문제
	* 자바 8에서는 이런 컴퓨터를 더 잘 활용할 수 있는 새로운 프로그래밍 스타일 제공

### 1.4.1 멀티 스레딩은 어렵다.
* 멀티 스레딩 > 스레드를 잘 제어하지 못하면 원치 않는 방식으로 데이터가 바뀔 수 있음.
	* 순차적인 모델보다 다루기가 어려움
* 자바 8은 스트림 API(java.util.stream)로 두 가지 문제 해결
	* 1. '컬렉션을 처리하면서 발생하는 모호함과 반복적인 코드 문제'
	* 2. '멀티코어 활용 어려움'
* 자주 반복되는 패턴으로 주어진 조건에 따라 데이터를 필터링하거나 추출하거나 그룹화하는 등의 기능 
* 포킹 단계(forking step)
	* 두 CPU를 가진 환경에서 리스트를 필터링할때 한 CPU는 리스트의 앞 부분을 처리하고,
	  다른 CPU는 리스트의 뒷부분을 처리하도록 요청

<br>
<br>

# 🚀 Chapter2. 동작 파라미터화 코드 전달하기
* 동작 파라미터화(behavior parameterization)
	* 아직은 어떻게 실행할 것인지 결정하지 않은 코드 블록
		* 이 코드 블록은 나중에 코드에서 호출 > 코드 블록의 실행은 나중으로 미뤄짐
	* 자주 바뀌는 요구사항에 효과적으로 대응 가능
	* 나중에 실행될 메서드의 인수로 코드 블록 전달 가능
	* 코드 블럭에 따라 메서드의 동작이 달라지게 됨.
* 거의 비슷한 코드가 반복 존재한다면 그 코드를 '추상화' 해라.

## 2.2 동작 파라미터화
* 프레디케이트 : 참 또는 거짓을 반환하는 함수
* 동작 파라미터화 : 메서드가 다양한 동작(또는 전략)을 받아서 내부적으로 다양한 동작 수행
	* 강점 : 컬렉션 탐색 로직과 각 항목에 적용할 동작을 분리할 수 있는 것
	* 한 메서드가 다른 동작을 수행하도록 재활용 > 유연한 API 만들 때 중요한 역할
## 2.3 복잡한 과정 간소화
### 2.3.1 익명 클래스
* 익명 클래스란?
	* 자바의 지역 클래스(블록 내부에 선언된 클래스)와 비슷한 개념
	* 이름이 없는 클래스
	* 클래스 선언과 인스턴스화 동시에 가능 > 즉석에서 필요한 구현 만들어서 사용

``` java
filterApples(inventory, new ApplePredicate() {
            @Override
            public boolean test(Apple apple) {
                return Color.RED.equals(apple.getColor());
            }
        });
```
* but, 익명 클래스로도 아직 부족 > 공간을 여전히 많이 차지
	* + 반복되어 지저분한 코드

### 2.3.3 람다 표현식 사용
``` java
filterApples(inventory, 
                (Apple apple) -> RED.equals(apple.getColor()));
```
* 이전 코드보다 훨씬 더 간결해짐

### 2.3.4 리스트 형식으로 추상화

``` java
public static <T> List<T> filter(List<T> list, Predicate<T> p) {
        List<T> result = new ArrayList<>();
        for (T e : list) {
            if (p.test(e)) {
                result.add(e);
            }
        }
        return result;
    }
```
* 사과 뿐만 아니라 바나나, 오렌지 등 다른 과일도 해당 메서드 사용 가능


## 2.4 실전 예제
* 동작 파라미터화 패턴 : 동작을 캡슐화한 다음, 메서드로 전달해서 메서드의 동작을 파라미터화

### 2.4.1 Comparator로 정렬
* java8의 List에는 sort 메서드 포함됨
* java.util.Comparator 객체를 이용해 sort의 동작을 파라미터화 할 수 있음
	* Comparator 구현해서 sort 메서드의 동작 다양화

```java
// 익명 클래스
inventory.sort(new Comparator<Apple>() {
            @Override
            public int compare(Apple a1, Apple a2) {
                return a1.getWeight().compareTo(a2.getWeight());
            }
        });


// 람다
inventory.sort((Apple a1, Apple a2)
                -> a1.getWeight().compareTo(a2.getWeight()));


// 더욱 간단한 방법
inventory.sort(Comparator.comparing(Apple::getWeight));
```

### 2.4.2 Runnable로 코드 블록 실행
* 자바에서는 Runnable 인터페이스를 사용하여 실행할 코드 블록을 지정할 수 있음
* 응답값 미존재함
```java
// java.lang.Runnable
public interface Runnable{
	void run();
}

// 익명 클래스
Thread t = new Thread(new Runnable(){
	void run(){
		System.out.println("Hello world");
	}
});

// 람다
Thread t = new Thread(() -> System.out.println("Hello world"));
```


### 2.4.3 Callable을 결과로 반환
* Runnable의 업그레이드 버전
* 응답값 존재
```java
// java.util.concurrent.Callable
public interface Callable<V>{
	V call();
}
```

**Comment by flyingtw** [comment]
아
