### ISSUE TITLE
Chapter.3 람다 표현식 ~ Chapter.4 스트림 소개

### ISSUE THREAD

**Issue by kyueun** [FireInStove/modern-java-in-action#2]
## 👑 스터디장
규은 ( @kyueun )

## 📖 스터디 범위
Chapter.3 람다 표현식 ~ Chapter.4 스트림 소개

## 🕧 스터디 일정
23/11/23 (목) 09시

**Comment by aimhigh53** [comment]
## ✏️ 2~3주차 

## 3.1 람다란 무엇인가?

**람다 표현식은** 메서드로 전달할 수 있는 익명함수를 단순화한 것이라고 할 수 있음. 파라미터 리스트, 바디, 반환형식, 발생할 수 있는 예외 리스트는 가질 수 있음

`
List<Apple> greenApples = filter(inventory,(Apple a) -> GREEN.equals(a.getColor()));
` 

## 3.2.1 함수형 인터페이스
함수형 인터페이스는 정확히 하나의 추상 메서드를 지정하는 인터페이스이다. 

`
...
public interface Runnable {
   void run();
}
...
`

함수형  인터페이스 -> 람다표현식으로 함수형 인터페이스의 추상 메서드 구현을 직접 전달 할 수 있으므로 전체 표현식을 함수형 인터페이스의 인스턴스로 취급할 수 있음.

## 3.2.2 함수 디스크립터
함수형 인터페이스의 추상 메서드 시그니처는 람다 표현식의 시그니처를 가리킴, 람다 표현식의 시그니처를 서술하는 메서드를 함수 디스크립터라고 부름. "() -> int"

일단 람다표현식은 변수에 할당하거나 함수형 인터페이스를 인수로 받는 메서드로 전달할 수 있으며, 함수형 인터페이스의 추상 메서드와 같은 시그니처를 갖는다는 사실을 기억하는 것으로 충분하다.

@FunctionalInterface?

@FunctionalInterface는 함수형 인터페이스임을 가리키는 어노테이션.
@FunctionalInterface로 인터페이스를 선언했지만 실제로 함수형 인터페이스가 아니면 컴파일러가 에러를 발생시킨다. 

##3.3 실행 어라운드 패턴
설정과 정리 과정은 대부분 비슷, 실제 자원을 처리하는 코드를 설정과 정리 두 과정이 둘러싸는 형태를 갖는다.

동작파라미터화> 동작전달> 동작 실행> 람다 전달

##3.4 함수형 인터페이스 사용
1. Predicate -> boolean 반환 lambda
2. Consumer -> 제네릭 형식 T 객체를 받아서 void를 반환하는 accept라는 추상 메서드를 정의
3. Function -> 제네릭 형식 T를 인수로 받아서 제네릭 형식 R 객체를 반환하는 추상 메서드 apply를 정의함 

## 3.6 메서드 참조

메서드 참조는 **가독성을 높이는 도구**
**before**

`
inventory.sort((Apple a1, Apple a2) -> a.getWeight().compareTo(a2.getWeight()));
`

**after**

`
inventory.sort((comparing(Apple::getWeight));
`

메서드 참조 만드는 방법
1. 정적 메서드 참조 Interger::parseInt
2. 다양한 형식의 인스턴스 메서드 참조 String::length
3. 기존 객체의 인스턴스 메서드 참조 object::getvalue

생성자 참조

`Supplier<Apple> c1 = Apple:new; `

##4.1 스트림이란?
스트림이 데이터 컬렉션 반복을 멋지게 처리하는 기능... 스트림을 이용하면 멀티스레드 코드를 구현하지 않아도 데이터를 투명하게 병렬로 처리할 수 있음

DataObject.stream()...

filter(sorted, map, collect) 같은 연산은 고수준 빌딩 블록으로 이루어져 있으므로 
특정 스레딩 모델에 제한되지 않고 자유롭게 어떤 상황에서든 사용할 수 있다.

스트림 API의 특징을 아래와 같이 요약
- 선언형
- 조립할 수 있음
- 병렬화 

##4.2 스트림 시작하기
- 연속된 요소: 컬렉션과 마찬가지로 스트림은 특정 요소 형식으로 이루어진 연속된 값 집합의 인터페이스를 제공한다
- 소스: 스트림은 컬렉션, 배열, I/O 자원등의 데이터를 소비함

- 데이터 처리 연산: 스트림은 함수형 프로그래밍 언어에서 언어에서 일반적인 지원하는 연산과 데이터베이스와 비슷한 연산을 지원한다

- 파이프라이닝: 대부분의 스트림 연산은 스트림 연산끼리 연결해서 커다란 파이프 라인을 구성할 수 있도록 스트림 자신을 반환한다

- 내부 반복:..

##4.3 스트림과 컬렉션

내부/외부반복: 
- 외부 반복: 컬렉션 인터페이스를 사용하려면 사용자가 직접 요소를 반복해야 한다
- 내부 반복: 스트림 라이브러리는 내부 반복

스트림 요약:
- 질의를 수행할 데이터소스
- 스트림 파이프라인을 구성할 중간 연산 연결
- 스트림 파이프라인을 실행하고 결과를 만들 최종 연산

**Comment by yougahee** [comment]
# 📖 3장. 람다 표현식
## 람다 표현식이란?
### 메서드로 전달할 수 있는 익명함수를 단순화한 것
### 람다의 구성
1) 파라미터 리스트
2) 화살표
3) 람다 바디

## 함수형 인터페이스
- 오직 하나의 추상 메서드를 지정하는 인터페이스
- 디폴트 메서드가 존재해도, 추상 메서드가 1개이면 함수형 인터페이스
- ex) Predicate<T>, Runnable, Comparator

## 함수 디스크립터
- 람다 표현식의 시그니처를 서술하는 메서드
- ex. Runnable 인터페이스의 추상메서드 run은 인수와 반환값(void)이 없으므로 인수와 반환값이 없는 시그니처로 생각할 수 있다.


## 실행 어라운드 패턴
- 순환 패턴 : 자원을 열고, 처리한 다음, 자원을 닫는 순서로 이루어진다.

```java
@FunctionalInterface
public interface BufferedReaderProcessor {
	String process(BufferedReader b) throws IOException;
}


public String processFile(BufferedReaderProcessor p) throws IOException;

// 실제 사용
String oneLine = processFile((BufferedReader) br -> br.readLine()); 
```

## Predicate
- boolean 을 반환한다.

## Consumer
- 제네릭 형식 T 객체를 받아서 void를 반환한다.

## Function
- T를 인수로 받아서, R을 return 한다.
- 더 나아가서.. (메모리 관리를 좀 더 효율적으로 하기 위해)
	- IntPredicate, LongPredicate, IntFuction 이런 것들이 있음.

## 형식 검사, 형식 추론, 제약
### 람다 표현식의 형식 검사 과정
1) 람다가 사용된 콘텍스트는 무엇일까? filter의 정의를 보자. 
2) 대상 형식은 Predicate<T> 임을 확인했다
3) 인터페이스의 추상 메서드는 무엇?
4) T를 인수로 받아 boolean을 반환하는 test 메서드

### 람다 > 지역변수 사용
- 람다에서 사용하는 지역변수는 실질적으로 final처럼 취급이 되어야 한다.
- 본사본의 값이 바뀌지 않아야 하므로 지역 변수에는 한번만 값을 할당해야 한다.

## 메서드 참조
- 때로는 메서드 참조를 사용하는 것이 가독성에 좋고, 자연스러울 수 있다.
1) 정적 메서드 참조
	- Integer::parseInt
2) 다양한 형식의 인스턴스 메서드 참조
	- String::length
3) 기존 객체의 인스턴스 메서드 참조
	- expensiveTransaction::getValue


## 생성자 참조
- ClassName::new 처럼 클래스명과 new 키워드를 이용해서 기존 생성자의 참조를 만들 수 있다.


# 📖 4장. 스트림
## 스트림이란?
- 스트림을 이용하면 선언형으로 컬렉션 데이터를 처리할 수 있다.
- 스트림을 이용하면 멀티스레드 코드를 구현하지 않아도 데이터를 투명하게 병렬로 처리할 수 있다.
- 데이터 처리 연산을 지원하도록 소스에서 추출된 연속된 요소

### 특징
- 선언형 : 더 간결하고 가독성이 좋아진다.
- 조립할 수 있음 : 유연성이 좋아진다 
- 병렬화 : 성능이 좋아진다


### 스트림의 두가지 중요한 특징
1) 파이프라이닝
- 스트림 연산은 스트림 연산끼리 연결해서 커다란 파이프라인을 구성할 수 있도록 스트림 자신을 반환한다.
2) 내부 반복
- 내부 반복을 지원한다.

### 컬렉션과 스트림의 차이
1) 데이터를 언제 계산하느냐
- 컬렉션은 현재 자료구조가 포함하는 모든 값을 메모리에 저장하는 구조
- 스트림은 요청할 때만 요소를 계산한다.
	- 특히, 사용자가 요청하는 값만 스트림에서 추출한다는 것이 핵심이다.
2) 데이터 반복 처리 방법
- 컬렉션 : 외부 반복
	- 사용자가 직접 요소를 반복해야 한다는 것
- 스트림 : 내부 반복
	- 반복을 알아서 처리하고 결과 스트림값을 어딘가에 저장
	- 반복과정을 우리가 신경쓰지 않아도 됨




### 스트림 이용하기
1) 질의를 수행할 데이터 소스
2) 스트림 파이프라인으 구성할 중간 연산 연결
- ex. filter, map, limit, sorted, distinct
3) 스트림 파이프라인을 실행하고 결과를 만들 최종연산
- ex. forEach, count, collect

**Comment by kyueun** [comment]
# 3. 람다 표현식
## 람다 표현식
메서드로 전달할 수 있는 익명 함수를 단순화한 것
- 익명
- 함수 : 특정 클래스에 종속되지 않음
- 전달
- 간결성

## 함수형 인터페이스
정확히 하나의 추상 메서드를 지정하는 인터페이스
- 디폴트 메서드가 있어도, 추상 메서드가 하나면 함수형 인터페이스

`@FunctionalInterface`
- 함수형 인터페이스임을 가리키는 어노테이션
- 이 어노테이션을 사용했지만 함수형 인터페이스가 아닌 경우 ( ex. 추상 메서드가 하나 이상 ) 컴파일러가 에러 발생

### 함수형 인터페이스 종류
1. `Predicate` : T -> boolean
2. `Consumer` : T -> void
3. `Function` : T -> R
4. `BiFunction` : (T, U) -> R
5. `Supplier` : () -> T

제네릭 함수형 외에도 특화된 형식의 인터페이스들도 존재
- ex. `IntPredicate`, `ToIntFunction<T>`, `IntToDoubleFunction` ...

## 함수 디스크립터
람다 표현식의 시그니처를 서술하는 메서드
- 함수가 어던 입력값을 받고, 어떤 반환값을 주는지에 대한 설명을 람다 표현식 문법으로 표현한 것
- ex. `Runnable` 의 함수 디스크립터는 `() -> void`

## 실행 어라운드 패턴
실제 자원을 처리하는 코드를 설정과 정리 두 과정이 둘러싸는 형태
- 순환 패턴 : 자원 열고 -> 처리 -> 닫음 ( == 설정 -> 처리 -> 정리 )
- `try-with-resources`

## 형식 검사, 형식 추론, 제약
### 형식 검사
- 형식 확인 과정 - `filter` 예제
    1. 람다가 사용된 컨텍스트는 무엇인가? -> `filter` 메서드 선언 확인
    2. 대상 형식? -> 두 번째 파라미터 `Predicate<Apple>` 기대
    3. 대상 형식인 `Predicate<Apple>`의 추상 메서드는?
    4. Apple 받아 boolean 반환하는 함수 디스크립터 확인
    5. 시그니처 일치하므로 완료

### 형식 추론
- 컴파일러는 대상 형식을 이용해서 함수 디스크립터 알 수 있음 -> 시그니처 추론 가능
- 명시적으로 형식 지정하지 않음 -> 가독성 향상

### 지역 변수 사용
람다 캡처링: 람다 표현식에서 외부에서 정의된 자유 변수를 활용
- 람다는 인스턴스 변수와 정적 변수를 자유롭게 캡처 가능 ( 참조 가능 )
- final로 선언되어 있거나, 실질적으로 final처럼 사용되어야 함
    - 지역 변수는 스택에 위치
    - 변수를 할당한 스레드가 사라져 변수 할당이 해제되었을 때에도 람다 실행 스레드에서는 변수 접근 가능해야 함
    - 자바에서는 람다가 원래 변수에 접근하도록 하지 않고, 변수의 복사본 제공
    - 복사본이 값이 바뀌면 안되므로 한 번만 값이 할당되어야 함

### 메서드 참조
`Apple::getWeight`
- 정적 메서드 참조 - `Integer::parseInt`
- 다양한 형식의 인스턴스 메서드 참조 - `String::length`
- 기존 객체의 인스턴스 메서드 참조 - `expensiveTransaction::getValue`

### 생성자 참조
```java
Supplier<Apple> c1 = Apple::new;
Apple a1 = c1.get();
```

# 4. 스트림 소개
## 스트림
데이터 처리 연산을 지원하도록 소스에서 추출된 연속된 요소

기능
- 선언형으로 컬렉션 데이터 처리 가능
- 멀티스레드 코드 구현 없이도 병렬 처리 가능 - `parallelStream`

자바8 스트림 API 특징
- 선언형: 간결, 가독성
- 조립할 수 있음: 유연성
- 병렬화: 성능

특징
- 파이프라이닝: 스트림 연산끼리 연결, 커다란 파이프라인을 구성할 수 있도록 스트림 자신을 반환
- 내부 반복

## 스트림과 컬렉션
- 데이터를 언제 계산하느냐
    - 컬렉션: 현재 자료구조가 포함하는 모든 값을 메모리에 저장 -> 모든 요소는 컬렉션에 추가하기 전에 계산되어야 함
    - 스트림: 이론적으로는 요청할 때만 요소를 계산
- 데이터 반복 처리 방법
    - 컬렉션: 외부 반복 - 사용자가 직접 요소를 반복
    - 스트림: 내부 반복 - 반복을 알아서 처리하고, 결과 스트림값을 어딘가에 저장해줌

## 스트림 연산
- 중간 연산: 연결할 수 있는 스트림 연산
    - 여러 중간 연산을 연결, 질의 생성 가능
    - lazy: 단말 연산을 스트림 파이프라인에 실행하기 전까지는 아무 연산도 수행하지 않음 -> 중간 연산을 합친 후, 합쳐진 중간 연산을 최종 연산으로 한 번에 처리
        - 최적화 효과 얻을 수 있음
            - 모든 요소가 아닌 대상 요소만 선택 - limit 연산, 쇼트서킷 ( 불필요한 연산 생략 )
            - 서로 다른 연산이 한 과정으로 병합 - 루프 퓨전
    - ex. `filter`, `sorted`
- 최종 연산: 스트림을 닫는 연산
    - 스트림을 반환하지 않고, 결과 도출
    - ex. `forEach`

**Comment by tmfrl1552** [comment]
# Chapter3. 람다 표현식
## 3.1 람다란 무엇인가?
* '람다 표현식' 이란?
	* 메서드로 전달할 수 있는 익명 함수를 단순화한 것
	* 이름은 없지만, 파라미터 리스트, 바디, 반환 형식, 발생할 수 있는 예외 리스트는 가질 수 있음

* 람다의 특징
	* 익명
		* 보통의 메서드와 달리 이름이 없으므로 '익명' 이라 표현.
	* 함수
		* 람다는 메서드처럼 특정 클래스에 종속되지 않으므로 함수라고 부름.
		* 하지만, 메서드처럼 파라미터 리스트, 바디, 반환 형식, 가능한 예외 리스트를 포함
	* 전달
		* 람다 표현식을 메서드 인수로 전달하거나 변수로 저장
	* 간결성
		* 익명 클래스처럼 많은 자질구례한 코드 구현할 필요 없음

* 람다 표현식은 파라미터, 화살표, 바디로 이루어짐
``` java
(Apple a1, Apple a2) -> a1.getWeight().compareTo(a2.getWeight());
```
	* 파라미터 리스트
		* Comparator의 compare 메서드 파라미터(사과 두 개)
	* 화살표
		* 화살표(->)는 람다의 파라미터 리스트와 바디를 구분
	* 람다 바디
		* 두 사과의 무게를 비교한다. 람다의 반환값에 해당하는 표현식

* java8의 유효한 람다 표현식
``` java
(String s) -> s.length() // 람다 표현식에는 return이 함축되어 있으므로 명시적으로 사용 안해도 됨
(Apple a) -> a.getWeight() > 150
(int x, int y) -> {
	System.out.println("Result: ");
	System.out.println(x + y);
} // 여러 행의 문장 포함 가능
() -> 42
(Apple a1, Apple a2) -> a1.getWeight().compareTo(a2.getWeight())
```
	* 표현식 스타일 람다
		* (parameters) -> expression
	* 블록 스타일 람다
		* (parameters) -> { statements; }
	* 정리 : 
		* 표현식 > ;, return 미작성
		* 블록 스타일 > {} 블록과 ;, return 작성

## 3.2 어디에, 어떻게 람다를 사용할까?
> 함수형 인터페이스라는 문맥에서 람다 표현식 사용

### 함수형 인터페이스
* 함수형 인터페이스란?
	* 정확히 하나의 추상 메서드를 지정하는 인터페이스
	* ex) Comparator, Runnable
* +) 많은 디폴트 메서드가 있더라도, ⭐️추상 메서드가 오직 하나면 함수형 인터페이스.⭐️
* 함수형 인터페이스로 뭘 할 수 있는지?
	* 람다 표현식으로 함수형 인터페이스의 추상 메서드 구현을 직접 전달할 수 있으므로,
	  전체 표현식을 함수형 인터페이스의 인스턴스로 취급할 수 있음.

### 함수 디스크립터
* 함수 디스크립터
	* 람다 표현식의 시그니처를 서술하는 메서드
	* Runnable 인터페이스의 유일한 추상 메서드 run은 인수와 반환값이 없으므로
	  Runnable 인터페이스는 인수와 반환값이 없는 시그니처로 생각할 수 있다.
* 왜 함수형 인터페이스를 인수로 받는 메서드에만 람다 표현식을 사용할 수 있는지?
	* 언어 설계자들이 언어를 더 복잡하게 만들지 않는 현재 방법 선택
	* 대부분의 자바 프로그래머가 하나의 추상 메서드를 갖는 인터페이스에 이미 익숙하다는 점도 고려

> @FunctionalInterface 란?
	> * 함수형 인터페이스를 가리키는 어노테이션
	> * 해당 어노테이션을 선언했지만, 실제로 함수형 인터페이스가 아닌 경우 컴파일러가 에러 발생

## 3.4 함수형 인터페이스 사용
> 자바8 라이브러리 설계자들은 java.util.function 패키지로 여러 가지 새로운 함수형 인터페이스를 제공

### 3.4.1 Predicate
* java.util.function.Predicate<T> 인터페이스
	* test라는 추상 메서드를 정의, test는 제네릭 형식 T의 객체를 인수로 받아 불리언 반환
	* T 형식의 객체를 사용하는 불리언 표현식이 필요한 상황에서 Predicate 인터페이스 사용 가능

### 3.4.2 Consumer
* java.util.function.Consumer<T> 인터페이스
	* 제네릭 형식 T 객체를 받아서 void를 반환하는 accept라는 추상 메서드 정의
	* T 형식의 객체를 인수로 받아서 어떤 동작을 수행하고 싶을 때 Consumer 인터페이스 사용

### 3.4.3 Function
* java.util.function.Function<T,R> 인터페이스
	* 제네릭 형식 T를 인수로 받아서 제네릭 형식 R 객체를 반환하는 추상 메서드 apply 정의
	* 입력을 출력으로 매핑하는 람다를 정의할 때 Function 인터페이스 활용

#### 기본형 특화
* 제너릭 파라미터에는 '참조형' 만 사용 가능
* 박싱 : 기본형을 참조형으로 변환하는 기능
* 언박싱 : 참조형을 기본형으로 변환하는 반대 동작
* 오토 박싱 : 박싱과 언박싱이 자동으로 이루어지는 것
* 변환 과정에는 비용 소모
	* 박싱한 값은 기본형을 감싸는 래퍼며 힙에 저장
	* 박싱한 값은 메모리를 더 소비하며 기본형을 가져올때도 메모리 탐색 과정 필요
* 자바 8 > 기본형을 입출력으로 사용하는 상황에서 오토박싱 동작을 피할 수 있도록 특별한 함수형 인터페이스 제공
``` java
public interface IntPredicate{
	boolean test(int t);
}
```
* 일반적으로 특정 형식을 입력받는 함수형 인터페이스 앞에는 형식명이 붙음
	* ex) DoublePredicate, IntConsumer, LongBinaryOperator ..


#### 예외, 람다, 함수형 인터페이스의 관계
* 함수형 인터페이스는 확인된 예외를 던지는 동작 미허용
* 예외를 던지는 람다 표현식을 만들려면 확인된 예외를 선언하는 함수형 인터페이스를 직접 정의하거나
  람다를 try/catch 블록으로 감싸야 함.


## 3.5 형식 검사, 형식 추론, 제약
* 대상 형식
	* 어떤 콘텍스트에서 기대하는 람다 표현식의 형식
* 특별한 void 호환 규칙
	* 람다의 바디에 일반 표현식이 있으면 void를 반환하는 함수 디스크립터와 호환됨
	  (물론 파라미터 리스트도 호환되어야 함)
``` java
//Predicate는 불리언 반환값을 갖는다.
Predicate<String> p = s -> list.add(s);

// Consumer는 void 반환값을 갖는다.
Consumer<String> c = s -> list.add(s);
```

### 형식 추론
* 자바 컴파일러는 람다 파라미터 형식 추론 가능
* 상황에 따라 명시적으로 형식을 포함히는 것이 좋을 때도 있고,
  형식을 배제하는 것이 가독성을 향상시킬 떄도 있음.


### 지역 변수 사용
* 람다 캡처링
	* 람다 표현식에서 익명 함수가 하는 것처럼 자유 변수(파라미터로 넘겨진 변수가 아닌 외부에서 정의된 변수)
	  를 활용하는 동작.
* 자유 변수의 제약
	* 람다는 인스턴스 변수와 정적 변수를 자유롭게 캡처(자신의 바디에서 참조)할 수 있도록 한다.
	* 그러려면 지역 변수는 명시적으로 final로 선언되어 있어야 하거나
	  실질적으로 final로 선언된 변수와 똑같이 사용되어야 함.
	 * 즉, 람다 표현식은 한 번만 할당할 수 있는 지역 변수를 캡처할 수 있음.
``` java
int portNumber = 1337;
Runnable r = () -> System.out.pringln(portNumber); // 에러 : 람다에서 참고하는 지역 변수는 실질적 final 처럼 취급
portNumber = 31338; 
```

#### 지역 변수의 제약
* 인스턴스 변수 > 힙에 저장 , 지역 변수 > 스택에 위치 
* 람다에서 지역 변수에 바로 접근할 수 있다는 가정하에 람다가 스레드에서 실행된다면
  변수를 할당한 스레드가 사라져서 변수 할당이 해제되었는데도 
  람다를 실행하는 스레드에서는 해당 변수에 접근하려 할 수 있음.
  * 따라서, 원래 변수에 접근을 허용하는 것이 아니라 자유 지역 변수의 복사본 제공
  * 복사본의 값이 바뀌지 않아야 하므로, 지역 변수에는 한 번만 값을 할당해야된다는 제약 생김


## 3.6 메서드 참조
* 메서드 참조
	* 특정 메서드만을 호출하는 람다의 축약형
	* 명시적으로 메서드명을 참조하면서, '가독성'을 높일 수 있음.
* 메서드 참조는 어떻게 활용?
	* 메서드명 앞에 구분자(::)를 붙이는 방식
``` java
1. (Apple apple) -> apple.getWeight() ===> Apple::getWeight
2. () -> Thread.currentThread().dumpStack() ===> Thread.currentThread()::dumpStack
3. (str, i) -> str.substring(i) ===> String::subString
4. (String s) -> System.out.println(s) ===> System.out::println
5. (String s) -> this.isValidName(s) ===> this::isValidName
```

### 메서드 참조를 만드는 방법
#### 1. 정적 메서드 참조
예를 들어 Integer 의 parseInt 메서드 > Integer::parseInt

#### 2. 다양한 형식의 인스턴스 메서드 참조
예를 들어 String의 length 메서드 > String::length

#### 3. 기존 객체의 인스턴스 메서드 참조
Transaction 객체를 할당받은 expensiveTransaction 지역 변수가 있고,
Transaction 객체에는 getValue 매서드가 있다면, 이를 expensiveTransaction::getValue로 표현 가능

* 세 번째 유형의 메서드 참조는 비공개 헬퍼 메서드를 정의한 상황에서 유용하게 활용
``` java
private boolean isValidName(String string){
	return Character.isUpperCase(string.charAt(0));
}

// Predicate<String>를 필요로 하는 적당한 상황에서 메서드 참조 가능
filter(words, this::isValidName)
```

## 3.6.2 생성자 참조
* ClassName::new 처럼 클래스명과 new 키워드를 이용해 기존 생성자의 참조를 만들 수 있음
	* 정적 메서드의 참조를 만드는 것과 비슷

<br>

# Chapter4. 스트림 소개
## 4.1 스트림이란 무엇인가?
* 스트림
	* 자바8 API에 새로 추가된 기능
	* 선언형(즉, 데이터를 처리하는 임시 구현 코드 대신 질의로 표현)으로 컬렉션 데이터 처리
	* 스트림이 데이터 컬렉션 반복을 멋지게 처리하는 기능!
	* 멀티스레드 코드를 구현하지 않아도 데이터를 투명하게 병렬로 처리 
* stream()을 parallelStream()으로 바꾸면 멀티코어 아키텍처에서 병렬로 실행 가능
	* 정확히 어떤 일이 일어나는지는 7장에서 설명
* 스트림의 다양한 이점
	* 1. 선언형으로 코드 구현 가능
		* 선언형 코드와 동작 파라미터화를 활용하면 변하는 요구사항에 쉽게 대응
		* if 조건문 등의 제어 블록 사용하여 동작 구현할 필요 없이 '저칼로리의 요리만 선택하라' 같은 동작의 수행 지정 
	* 2. filter, sorted, map, collect 같은 여러 빌딩 블록 연산을 연결해서
	     복잡한 데이터 처리 파이프라인을 만들 수 있음
* filter(or sorted, map, collect) 같은 연산은 고수준 빌딩 블록으로 이루어져 있으므로
  특정 스레딩 모델에 제한되지 않고 자유롭게 어떤 상황에서든 사용 가능
  	* 내부적으로 단일 스레드 모델에 사용할 수 있지만, 멀티코어 아키텍처를 최대한 투명하게 활용할 수 있게 구현
  	* 데이터 처리 과정을 병렬화하면서 스레드와 락을 걱정할 필요가 없음.

 > 기타 라이브러리: 구아바, 아파치, 람다제이
 	> 컬렉션을 제어하는데 도움이 되는 다양한 라이브러리 존재
 	> 1. 구아바 : 구글에서 만듬, 멀티맵/멀티셋 등 추가적 컨테이너 클래스 제공
 	> 2. 아파치 : 공통 컬렉션 라이브러리도 비슷한 기능 제공
 	> 3. 람다제이 : 함수형 프로그래밍에서 영감을 받은 선언형으로 컬렉션을 제어하는 다양한 유틸리티 제공


 * 자바 8 의 스트림 API 특징 요약
 	* 선언형 : 더 간결하고 가독성이 좋아진다.
 	* 조립할 수 있음 : 유연성이 좋아진다.
 	* 병렬화 : 성능이 좋아진다.


## 4.2 스트림 시작하기
* 스트림이란 정확히 뭘까
	* 데이터 처리 연산을 지원하도록 소스에서 추출된 연속된 요소
		* 연속된 요소
			* 컬렉션과 마찬가지로 스트림은 특정 요소 형식으로 이루어진 연속된 값 집합의 인터페이스 제공
			* 컬렉션의 주제는 데이터이고, 스트림의 주제는 계산.
				* 컬렉션 : 시간과 공간의 복잡성과 관련된 요소 저장 및 접근 연산이 주
				* 스트림 : filter, sorted, map 처럼 표현 계산식이 주
		* 소스
			* 스트림은 컬렉션, 배열, I/O 자원 등의 데이터 제공 소스로부터 데이터 소비
			* 리스트로 스트림을 만들면 스트림의 요소는 리스트와 같은 순서 유지
		* 데이터 처리 연산
			* 함수형 프로그래밍 언어에서 일반적으로 지원하는 연산과 데이터베이스와 비슷한 연산 지원
* 스트림의 중요한 두가지 특징
	* 파이프라이닝
		* 대부분 스트림 연산은 스트림 연산끼리 연결해서 커다란 파이프라인 구성할 수 있도록 스트림 자신을 반환
	* 내부 반복
		* 반복자를 이용해서 명시적으로 반복하는 컬렉션과는 달리 스트림은 내부 반복 지원

* filter, map, limit, collect
	* filter : 람다를 인수로 받아 스트림에서 특정 요소를 제외
	* map : 람다를 이용해서 한 요소를 다른 요소로 변환하거나 정보 추출
	* limit : 정해진 개수 이상의 요소가 스트림에 저장되지 못하게 스트림 크기 축소
	* collect : 스트림을 다른 형식으로 변환


## 4.3 스트림과 컬렉션
* 데이터를 '언제' 계산하느냐가 컬렉션과 스트림의 가장 큰 차이
	* 컬렉션 : 현재 자료구조가 포함하는 모든 값을 메모리에 저장하는 자료구조
		* 컬렉션의 모든 요소는 컬렉션이 추가하기 전에 계산되어야 함.
	* 스트림 : 요청할 때만 요소를 계산하는 고정된 자료구조
* 스트림은 단 한 번만 소비할 수 있다는 점 명심하기!!


### 4.3.2 외부 반복와 내부 반복
* 외부 반복
	* 컬렉션 인터페이스를 사용하려면 사용자가 직접 요소를 반복(ex. for-each 사용)
* 내부 반복
	* 스트림 라이브러리는 반복을 알아서 처리하고 결과 스트림값을 어딘가에 저장
	* 작업을 투명하게 병렬로 처리하거나 더 최적화된 다양한 순서로 처리할 수 있음
* 스트림 라이브러리의 내부 반복은 데이터 표현과 하드웨어를 활용한 병렬성 구현을 '자동으로 선택'

<br>

## 4.4 스트림 연산
``` java
List<String> names = menu.stream() // 요리에서 스트림 얻기
						 .filter(dish -> dish.getCalories() > 300) // 중간 연산
						 .map(Dish::getName) // 중간 연산
						 .limit(3) // 중간 연산
						 .collect(toList()); // 스트림을 리스트로 변환(최종 연산)
```
> 두 그룹으로 구분
	> * filter, map, limit는 서로 연결되어 파이프라인 형성
	> * collect로 파이프라인을 실행한 다음에 닫음

* 중간 연산
	* 연결할 수 있는 스트림 연산
* 최종 연산
	* 스트림을 닫는 연산

### 중간 연산
* filter, sorted 같은 중간 연산은 다른 스트림을 반환
	* 여러 중간 연산을 연결해서 질의 만들 수 있음
* 중요한 특징
	* 단말 연산을 스트림 파이프라인이 실행하기 전까지는 아무 연산도 수행하지 않는다 > 즉 게으름!!
	* 중간 연산을 합친 다음에 중간 연산을 최종 연산으로 한 번에 처리
* 루프 퓨전 : 서로 다른 연산이지만 한 과정으로 병합


### 최종 연산
* 스트림 파이프라인에서 결과를 도출
* 보통 최종 연산에 대해 List, Integer, void 등 스트림 이외의 결과가 반환


### 스트림 이용하기
* 스트림 이용 과정 > 세가지 요약
``` java
* 질의를 수행할 (컬렉션 같은) 데이터 소스
* 스트림 파이프라인을 구성할 중간 연산 연결
* 스트림 파이프라인을 실행하고 결과를 만들 최종 연산

**Comment by tmfrl1552** [comment]
김태완 안함.
