### ISSUE TITLE
Chapter.5 스트림 활용

### ISSUE THREAD

**Issue by flyingtw** [FireInStove/modern-java-in-action#3]
## 👑 스터디장
태완 ( @flyingtw  )

## 📖 스터디 범위
Chapter.5 스트림 활용

## 🕧 스터디 일정
23/12/07 (목) 09시

**Comment by flyingtw** [comment]
- filter와 collec 연산을 지원하는 스트림 API를 이용해서 데이터 컬렉션 반복을 내부적으로 처리할 수 있다.
- filter 메서드에 필터링 연산을 인수로 넘겨주면 된다.

# 5.1 필터링
## 5.1.1 프레디케이트로 필터링
- 프레디케이트(불리언을 반환하는 함수)를 인수로 받아서 프레디케이트와 일치하는 모든 요소를 포함하는 슽릠을 반환한다.
-  .filter(Dish::isVegetarian) 과 같이 boolean 필터를 걸 수 있다.
## 5.1.2 고유 요소 필터링
- 고유 요소 스트림 반환인 distinct 메서드도 지원한다.
- filter 된거에 중복을 제거하는 요소

# 5.2 스트림 슬라이싱
- 스트림의 요소를 선택한거나 스킵하는 다양한 방법을 설명한다.
## 5.2.1 프렝디케이트를 이용한 슬라이싱
- 자바9는 스트림의 요소를 효과적으로 선택할 수 있도록 takeWhile, dropWhile 두가지 새로운 메서드를 지원한다.
### TAKEWHILE
- 스트림이 순차 정렬 되어있다고 할때 takewhile 이후엔 스트림을 슬라이스, 즉 잘라내버려서 더 연산하지 않아도 되도록 하는것이다.
### DROPWHILE
-  TAKEWHILE의 반대
## 5.2.2 스트림 축소
- limit을 이용해서 갯수 제한을 걸 수 있다.
## 5.2.3 요소 건너뛰기
- limit과 반대로 처음 n개를 건너뛰는 skip도 존재한다.

# 5.3 매핑
- 특정 객체에서 특정 데이터를 선택하는 작업이 필요할 수 있다.
- 이는 map과 flatMap메서드를 통해 구현한다.
## 5.3.1 스트림의 각 요소에 함수 적용하기
- .map(String::length) 또는 .map(Dish::getName) 과 같이 함수를 이용해서 새로운 List를 만들 수 있다.
## 5.3.2 스트림 평면화
- String두개를 가진 List<String> 의 문자 하나하나를 다루고 싶을땐 flatMap을 이용해서 각각의 배열을 하나의 String 스트림으로 평면화하여 처리할 수 있다.

# 5.4 검색과 매칭
- allMatch, anyMatch, noneMatch, findFirst, findAny 등 검색의 매칭을 할 수 있다.
## 5.4.1 프레디케이트가 적어도 한 요소와 일치하는지 확인
- .anyMatch(Dish::isVegetarian)
## 5.4.2 프레디케이트가 모든 요소와 일치하는지 검사
- allMatch는 모두 맞는지 검사한다.
## NONEMATCH
- allMatch의 반대 연산 (모두 아니여야 한다.)
## 5.4.3 요소 검색
- .findAny()로 하나를 검색 할 수 있다.

### Optional이란?
- null값을 표현할때 사용

## 5.4.4 첫 번째 요소 찾기
- findFirst는 첫번째 요소를 찾는것이다.
- findAny와 차이점은 ? 
=> 병렬성 때문이다. 순서가 상관없다면 제약이 적은 findAny를 사용하도록 하자.

# 5.5 리듀싱
- 값이 하나가 나올때까지 계속 돌리는거다.
- 하나가 나올때까지 하는거라 폴드라고도 한다.

## 5.5.1 요소의 합
- numbers.stream().reduce(1, (a, b) -> a + b); 는 numbers리스트의 각각의 값을 더해서 하나가 남을때까지 계속 연산한다.
- 누적값을 계속 유지하면서 계산하는것이다.
- 위 코드는 numbers.stream().reduce(0, Integer::sum)으로 표현 할 수 있다.
- 초기값이 없으면 아예 합계 자체가 없기때문에 null을 표현 할 수 있는 Optional을 반환한다.

## 5.5.2 최댓값과 최솟값
- (x, y) -> x<y ? x : y 를 Integer::min 으로도 표현 할 수 있다.

- 스트림 연산은 결국 모든 요소가 버퍼에 추가되어 있어야 한다. 따라서 소수의 역순 같은 무한값을 표현 할 순 없다.

# 5.6 (예제)
##5.7.1 기본형 특화 스트림
- IntStream, DoubleStream 과 같이 .sum()과 같이 최종 결과 값의 형식이 정해져 있는 약속된 메서드를 사용할때 기본형을 미리 정해놓는 특화 스트림을 제공한다.
- 숫자 스트림으로 매핑할때는 mapToInt, mapToDouble, mapToLong 세가지 메서드를 가장 많이 사용한다.
- OptionalInt 와 같이 기본형 특화 스트림 버전도 제공한다.
- OptionalInt maxCalories = menu.stream().mapToInt(Dish::getCalories).max(); 에서
int max = maxCalories.orElse(1); 과 같이 null일경우 최대값을 미리 선언해 놓을 수 있다.

##5.7.2  숫자 범위
- range(처음, 마지막 값 제외), rangeClosed(처음, 마지막값 포함) 하여 범위를 정할 수도 있다.
#5.8 스트림 만들기
## 5.8.1 값으로 스트림 만들기
- stream.of("hello", "world")와 같이 문자열 스트림을 스트림 생성시 만들어버릴수도 있다
- Stream.empty()로 값을 비울 수도 있다.
## 5.8.2 null이 될 수 있는 객체로 스트림 만들기
- Stream.ofNullable을 이용해 null일 수 있는 stream을 만들 수 있다.
## 5.8.3 배열로 스트림 만들기 
- int[] numbers = {2, 3, 4, 5} 를 Arrays.stream(numbers)로 하나의 스트림으로 만들 수 있다.
## 5.8.4 파일로 스트림 만들기
- Files.lines는 주어진 파일의 행 스트림을 문자열로 반환한다.
## 5.8.5 함수로 무한 스트림 만들기
- 스트림은 무한으로 만들 수 있다. (단 limit을 걸어야 한다.)
- 이를 언바운드 스트림이라고 한다. 이게 바로 컬렉션과의 가장 큰 차이점이다.
- iterate : 무한으로 스트림 만들 수 있다.
- generate : iterate는 초기값을 입력을 받는다면, generate는 초기값 없이 Supplier<T>를 인수로 받아서 새로운 값을 생성한다. (limit은 꼭 필요함)

**Comment by kyueun** [comment]
# 5. 스트림 활용
## 필터링
1. 프레디케이트로 필터링 - `filter`
    - 프레디케이트를 인수로 받아서 일치하는 요소 포함하는 스트림 반환
2. 고유 요소 필터링 - `distinct`

## 스트림 슬라이싱
1. 프레디케이트 이용
    - `takeWhile`
        - 조건에 맞는 요소 나왔을 때 반복 작업 중단
        - 스트림에 프레디케이트 적용해 슬라이스
    - `dropWhile`
        - `takeWhile`과 정반대
        - 프레디케이트가 거짓이 되는 지점까지의 요소 버림
3. 스트림 축소 - `limit`
4. 요소 건너뛰기 - `skip`
    - 처음 n개 요소를 제외한 스트림 반환

## 매핑
1. 각 요소에 함수 적용 - `map`
2. 스트림 평면화 - `flatMap`
    - `Stream<String[]>` -> `flatMap(Arrays::stream)` -> `Stream<String>`

## 검색과 매칭
1. 프레디케이트가 적어도 한 요소와 일치 - `anyMatch`
2. 프레디케이트가 모든 요소와 일치 - `allmatch`
3. 프레디케이트와 일치하는 요소 없음 - `noneMatch`
4. 요소 검색 - `findAny`
    - `Optional`로 반환
5. 첫 번째 요소 찾기 - `findFirst`
    - `Optional`로 반환

## 리듀싱
- `reduce`
- 요소를 조합해 복잡한 질의 표현
    - ex) sum, max, ...

## 숫자형 스트림
기본형 특화 스트림
- `IntStream`, `DoubleStream`, ...
- `mapToInt` 등으로 일반 스트림을 특화 스트림으로 변환
- `boxed` 통해서 특화 스트림을 일반 스트림으로 변환
- 숫자 범위 지정 가능 - `rangeClosed`

## 스트림 만들기
1. 값으로 스트림 만들기 - `Stream.of`
2. null이 될 수 있는 객체로 스트림 만들기 - `Stream.ofNullable`
3. 배열로 스트림 만들기 - `Arrays.stream`
4. 파일로 스트림 만들기 - `Files.lines`
5. 함수로 무한 스트림 만들기
    - 무한 스트림: 크기가 고정되지 않은 스트림
    - 보통 `limit` 함수와 연결해서 사용
    - `Stream.iterate`
        - 언바운드 스트림: `Stream.iterate`와 같이 요청할 때마다 값을 생산, 끝이 없음
        - ```java
            Stream.iterate(0, n->n+2)
                .limit(10)
                .forEach(System.out::println);
            ```
    - `Stream.generate`
        - Supplier를 인수로 받아 새로운 값 생성
        - ```java
            Stream.generate(Math::random)
                .limit(5)
                .forEach(System.out::println);
            ```

**Comment by yougahee** [comment]
# 📖 5장. 스트림

## 5.1 필터링
### Predicate로 필터링
- filter > 해당 조건에 true 인 값만 필터링

### 공유 요소 필터링
- distinct > 중복 값을 제거

## 5.2 스트림 슬라이싱
- 자바 9의 새 기능
- 슬라이싱이란 스트림의 요소를 선택하거나 스킵하는 다양한 방법을 말한다.

#### 1) 프레디케이트를 이용한 슬라이싱
- takeWhile(Predicate)
	- 해당 조건에 일치하지 않을 때, 해당 작업을 멈추고 앞의 스트림만 return 한다.
	- ```java
		//TEST1
		var list = Arrays.asList(1, 2, 3, 4, 10, 20, 30);

        var count = list.stream().takeWhile(x -> x < 5).count();
        // 결과는 4
        System.out.println(count);


        // TEST2
        var list = Arrays.asList(1, 10, 3, 4, 10, 20, 30);

        var count = list.stream().takeWhile(x -> x < 5).count();
        // 결과 : 1
        System.out.println(count);


		```

- dropWhile(Predicate)
	- 조건이 일치할 때를 기준으로 그 이후 데이터 return (이전 데이터 버리기)

#### 2) 스트림 축소
- limit(n) > 스트림에서 n개까지만 가져오기


#### 3) 요소 건너뛰기
- skip(n) > 스트림에서 처음의 n개를 건너뛰고 가져오기


## 5.3 매핑

### 예제 1. [ "hello", "World" ] 리스트에서 고유 character를 뽑아내라

- 테스트1. 실패
	- List<Stream<String>> 이 되면서.. 원하는 결과 도출하지 못함
```java
var list = Arrays.asList("hello", "World");

var word = list.stream()
                .map(x -> x.split("")) // Stream<String[]>
                .map(Arrays::stream) // List<Stream<String>>
                .distinct()
                .collect(toList());


```

- 테스트2. flatMap 사용
	- 결과 : h e l o W r d 
	- flatmap : 스트림의 각 값을 다른 스트림으로 만든 다음에 모든 스트림을 하나의 스트림으로 연결하는 기능을 수행한다.
```java
		var list = Arrays.asList("hello", "World");

        var uniqueCharacters = list.stream()
                .map(x -> x.split(""))
                .flatMap(Arrays::stream)
                .distinct()
                .collect(Collectors.toList());


        for (var tt : uniqueCharacters) {

            System.out.print(tt + " ");
        }

```

## 5.4 검색과 매칭

### 스트림 쇼트서킷 기법
- 쇼트서킷이란?
	- 표현식에서 하나라도 거짓이면 다른 값들과 상관없이 거짓이 됨
- 자바의 && 와 || 와 같은 연산을 활용

#### anyMatch()
- 적어도 하나의 요소가 일치하는지 확인
- return 은 boolean으로

#### allMatch()
- 모든 요소가 일치하는지 확인

#### noneMatch()
- allMatch()와 완전 반대
- 모든 요소가 다 일치하지 않는지 확인

### 요소 검색 

#### findAny()
- 스트림에서 일치하는 임의의 요소

#### findFirst()
- 스트림에서 일치하는 첫번째 요소

## 5.5 리듀싱
- 스트림 요소를 조합하여 도출하는 것이라고 보면 됨
#### reduce
- 예시
	- 해당 예시에서 reduce 다음에 바로 나오는 1 은 초기화 숫자이다.
	- 만약, 초기화 숫자를 정하지 않는다면 결과값은 Optional로 될 것임.
```java

int product = numbers.stream().reduce(1, (a,b) -> a*b);

```
- 해당 예시 외에도 최댓값, 최솟값을 도출할 수 있음.


## 5.7 숫자형 스트림

### 기본형(Primitive) 특화 스트림
- 총 3가지, IntStream, DoubleStream, LongStream 을 제공

```java

int calories = menu.stream()
					.mapToInt(Dish::getCalories) // IntStream을 반환
					.sum();

```

### 객체 스트림으로 복원하기
- 숫자 스트림을 만든 후에, 다시 원상태로 바꾸고 싶어!!

```java
IntStream intStream = menu.stream().mapToInt(Dish::getCalories);

// 박싱하여 객체 스트림으로 복원
Stream<Integer> stream = intStream.boxed();
```

### 기본값 : OptionalInt
- OptionalInt, OptionalDouble, OptionalLong > 3가지 기본형 특화 스트림 버전도 제공


### 숫자 범위
- 특정 범위의 숫자를 사용하고자 할 때 사용
- range > 시작과 종료값을 결과에 포함하지 않음
- rangeClosed > 시작과 종료값을 결과에 포함함


## 5.8 스트림 만들기
- 일련의 값, 배열 파일 등에서 스트림 만드는 방법

### 값으로 스트림 만들기
```java
Stream<String> stream = Stream.of("gaga", "ga", "hi", "hee");
stream.map(String::toUpperCase).forEach(System.out::println);

// empty 메서드로 스트림 비우기
var emptyStream = Stream.empty();
```

### 배열로 스트림 만들기
```java
int[] numbers = {2,3,5,7,11,13};
int sum = Arrays.stream(numbers).sum();
```


### 함수로 무한 스트림 만들기
- 무한 스트림이란 고정된 컬렉션에서 고정된 크기의 스트림을 만드는 것과는 달리, 크기가 고정되지 않은 스트림을 만드는 것
- 이런 스트림을 언바운드 스트림이라고 한다.

#### iterate 메서드
```java
Stream.iterate(0, n -> n+2)
		.limit(10)
		.forEach(System.out::println);
```

#### generate
- generate는 Supplier<T>를 인수로 받아서 새로운 값을 생성한다.

**Comment by tmfrl1552** [comment]
# Chapter5. 스트림 활용

## 5.1 필터링
### 5.1.1 프레디케이트로 필터링
* 'filter' 메서드
	* 프레디케이트(불리언 반환 함수)를 인수로 받아 프레디케이트와 일치하는 모든 요소를 포함하는 스트림을 반환


### 5.1.2 고유 요소 필터링
* 스트림은 고유 요소로 이루어진 스트림을 반환하는 'distinct' 메서드도 지원
	* 고유 여부는 스트림에서 만든 객체의 hashCode, equals로 결정됨. 

## 5.2 스트림 슬라이싱
> 스트림의 요소를 선택하거나 스킵하는 다양한 방법 설명

### 5.2.1 프레디케이트를 이용한 슬라이싱
* 자바 9 > 스트림의 요소를 효과적으로 선택할 수 있도록 'takeWhile', 'dropWhile' 두 가지 메서드 지원

#### TAKEWHILE 활용
``` java
List<Dish> sliceMenu1 =
	specialMenu.stream()
			   .takeWhile(dish -> dish.getCalories < 320)
			   .collect(toList());
``` 
* takeWhile ➡️ 조건에 참이 아닐 경우(거짓일 경우), 바로 멈춤.
* 무한 스트림을 포함한 모든 스트림에 프레디케이트를 적용해 스트림을 슬라이스할 수 있음
* 리스트가 이미 정렬돼있다는 가정하에 사용
* 아주 많은 요소를 포함하는 큰 스트림에서는 상당한 차이가 될 수 있음.

<br>

#### DROPWHILE
``` java
List<Dish> sliceMenu1 =
	specialMenu.stream()
			   .dropWhile(dish -> dish.getCalories < 320)
			   .collect(toList());
``` 
* dropWhile <-> takeWhile(정반대 역할)
* dropWhile > 프레디케이트가 거짓이 되면 그 지점에서 작업을 중단하고, 남은 모든 요소 반환.
* 무한한 남은 요소를 가진 무한 스트림에서도 동작.


### 5.2.2 스트림 축소
* 스트림은 주어진 값 이하의 크기를 갖는 새로운 스트림을 반환하는 'limit(n)' 메서드 지원
	* 스트림이 정렬되어 있으면 최대 요소 n개 반환
* 소스가 정렬되어 있지 않았다면 limit의 결과도 정렬되지 않은 상태로 반환.


### 5.2.3 요소 건너뛰기
* 처음 n개 요소를 제외한 스트림을 반환하는 'skip(n)' 메서드 지원
* n개 이하의 요소를 포함하는 스트림에 skip(n)을 호출하면 빈 스트림 반환

<br>

## 5.3 매핑
> 스트림 API의 map과 flatMap 메서드는 특정 데이터를 선택하는 기능 제공

### 5.3.1 스트림의 각 요소에 함수 적용하기
* 함수로 인수로 받는 'map 메서드' 지원
* 인수로 제공된 함수는 각 요소에 적용되며 함수를 적용한 결과가 새로운 요소로 매핑된다.


### 5.3.2 스트림 평면화
* 'flapMap'은 각 배열을 스트림이 아니라 스트림의 콘텐츠로 매핑
* map(Arrays::stream)과 달리 flapMap은 하나의 평면화된 스트림 반환.


## 5.4 검색과 매칭
> allMatch, anyMatch, noneMatch, findFirst, findAny 등 다양한 유틸리티 메서드 제공

* anyMatch : 프레디케이트가 주어진 스트림에서 적어도 한 요소와 일치하는지 확인
	* 불리언을 반환하므로 최종 연산이다.
* allMatch : 스트림의 모든 요소가 주어진 프레디케이트와 일치하는지 검사.
* noneMatch : 주어진 프레디케이트와 일치하는 요소가 '없는지' 확인.
> anyMatch, allMatch, noneMatch 세 메서드는 스트림의 쇼트서킷 기법,
> 즉 자바의 &&, || 와 같은 연산을 활용한다.


### 5.4.3 요소 검색
* findAny : 현재 스트림에서 임의의 요소 반환.
	* 다른 스트림 연산과 연결해서 사용 가능
* 스트림 파이프라인은 내부적으로 단일 과정으로 실행할 수 있도록 최적화
	* 즉, 쇼트서킷을 이용해서 결과를 찾는 즉시 실행 종료.

<br>

#### Optional 이란?
Optional<T> 클래스(java.util.Optional) 는 값의 존재나 부재 여부를 표현하는 컨테이너 클래스



### 5.4.4 첫 번쨰 요소 찾기
* findFirst : 스트림의 첫 번째 요소 반환


#### findFirst와 findAny는 언제 사용하나?
* findFirst/findAny 모두 필요한 이유 > 병렬성
	* 병렬 실행에서는 첫 번째 요소를 찾기 어려우므로, (parallelStream..?)
	  요소 반환 순서가 상관 없다면 병렬 스트림에서는 제약이 적은 findAny 사용


## 5.5 리듀싱
* '리듀싱 연산' 이란?
	* 모든 스트림 요소를 처리해서 값으로 도출하는 연산
	* 함수형 프로그래밍 용어 > 폴드 (종이를 작은 조각이 될 때까지 반복적으로 접는다는 의미)
* reduce 
	* 스트림이 하나의 값으로 줄어들 때 까지 람다는 각 요소를 반복해서 조합
	* 두 개의 인수 가짐 
		* 1. 초깃값
		* 2. 두 요소를 조합해서 새로운 값을 만드는 BinaryOperator<T>
``` java
int sum = numbers.stream.reduce(0, (a, b) -> a + b); // 모든 요소 더하기
int product = numbers.stream.reduce(1, (a, b) -> a * b); // 모든 요소 곱하기
int sum = numbers.stream.reduce(0, Integer::sum); // 정적 sum 메서드 참조를 이용
```


#### 초깃값 없음
초깃값을 받지 않도록 오버로드된 reduce -> Optional 객체 반환
	* 스트림에 아무 요소도 없는 상황 고려
``` java
Optional<Integer> sum = numbers.stream.reduce((a, b) -> a + b);
```

#### reduce 메서드의 장점과 병렬화
* reduce를 이용하면 내부 반복이 추상화되면서 내부 구현에서 병렬로 reduce 실행 가능

<br>

## 5.7 숫자형 스트림
### 5.7.1 기본형 특화 스트림
* 자바8에서는 세 가지 기본형 특화 스트림 제공
	* int 요소에 특화된 IntStream
	* double 요소에 특화된 DoubleStream
	* long 요소에 특화된 LongStream
* 숫자 스트림의 합계를 계산하는 sum, 최댓값 요소를 검색하는 max 같이 
  자주 사용하는 숫자 관련 리듀싱 연산 수행 메서드 제공

#### 숫자 스트림으로 매핑
* 스트림을 특화 스트림으로 변환할 때는 > mapToInt, mapToDouble, mapToLong 가장 많이 사용
* map과 정확히 같은 기능 수행, but Stream<T> 대신 특화된 스트림 반환
``` java
int calories = menu.stream()
				   .mapToInt(Dish::getCalories) // IntStream 반환
				   .sum();
```
* IntStream > max, min, average 등 다양한 유틸리티 메서드 지원

#### 객체 스트림으로 복원하기
* boxed 메서드를 이용해 특화 스트림을 일반 스트림으로 변환
``` java
IntStream intStream = menu.stream().mapToInt(Dish::getCalories);
Stream<Integer> stream = intStream.boxed(); // 숫자 스트림을 스트림으로 변환
```

#### 기본값: OptionalInt
* OptionalInt 를 이용해 IntStream의 최댓값 요소 검색
	* 스트림에 요소가 없을 수도 있으므로!

<br>

### 5.7.2 숫자 범위
* java8의 IntStream, LongStream에서는 range, rangeClosed라는 두 가지 정적 메서드 제공
* range
	* 시작값과 종료값이 결과에 포함되지 않음
* rangeClosed
	* 시작값과 종료값이 결과에 포함

## 5.8 스트림 만들기
### 5.8.1 값으로 스트림 만들기
* 임의의 수를 인수로 받는 정적 메서드 Stream.of를 이용해서 스트림 생성 가능

### 5.8.3 배열로 스트림 만들기
* 배열을 인수로 받는 정적 메서드 Arrays.stream 을 이용해서 스트림 생성 가능

### 5.8.5 함수로 무한 스트림 만들기
* 스트림 API 는 함수에서 스트림을 만들 수 있는 두 정적 메서드 Stream.iterate와 Stream.generate 제공
	* 무한 스트림(크기가 고정되지 않은 스트림) 생성 가능

#### iterate 메서드
* 초깃값과 람다를 인수로 받아 새로운 값을 끊임없이 생산

#### generate 메서드
* 요구할 때 값을 계산하는 무한 스트림 생성
* iterate와 달리 생산된 값을 연속적으로 계산하지 않음
* Supplier<T>를 인수로 받아 새로운 값 생산

**Comment by aimhigh53** [comment]
## ✏️ 4~5주차 

## 5.1 filtering

1. predicate filtering

`
List<Dish> vegetarianMenu = menu.stream()
							  .filter(Dish::isVegetarian)
                                                            .collect(toList());
` 

2. 고유 요소 filtering
`
List<Dish> vegetarianMenu = menu.stream()
							   .filter(i -> i % 2 ==0)
                                           		   .distinct()                         
                                                             .forEach(System.out::printtln);
` 

## 5.2 스트림 슬라이싱

1) Predicate을 이용한 슬라이싱(takeWhile, dropWhile)

위에 사용한 filter()를 이용해서 filter(dish -> dish.getCalories() < 300 ) 다음과 같이 조건을 주면 된다. 하지만 이미 정렬되어 있는 리스트의 경우라면 300이상의 칼로리인 요소가 나온 시점부터는 반복을 중단해도 된다. 이런 케이스에 takeWhile을 사용한다.

2)스트림 축소, 요소 스킵
limit(n)을 통해서 주어진 값 n개의 요소를 가지는 스트림을 반환하고, skip(n)은 처음 n개의 요소를 제외, 이후 요소 만을 포함하는 스트림을 반환함.limit와 skip은 결과적으로 상호보완적인 연산 수행

## 5.3 매핑

특정 객체에서 특정데이터를 선택하는 작업

ex. Dish객체를 요소로 가지고 있는 스트림 ⇒ 매핑 ⇒ Dish객체의 calories값을 요소로 가지는 스트림

(1) 스트림의 각 요소에 함수 적용하기
map메서드는 함수를 인수로 받는데 이때 제공받은 함수를 각 요소에 적용시켜서 나온 결과가 새로운 요소로 매핑된다.

map메서드의 출력스트림은 인수로 제공받은 함수의 리턴타입 T에 대한 Stream가 된다.

(2) 스트림 평면화
map 메소드 사용
- map과 Arrays.srtream
- flatmap 사용 예시를 보면서 스트림 평면화를 확인

## 5.4 검색과 매칭
1) Predicate를 이용한 요소 검사 (anyMatch, allMatch, noneMatch)
2) 요소 검색 (findAny, findFirst)

위의 3가지 메서드는 boolean을 반환하며 자바의 &&, ||와 같은 스트림의 쇼트서킷 기법 쇼트서킷은 &&, || 같이 앞 조건식의 결과에 따라 뒤 조건식의 실행여부를 결정하는 논리연산자

## 5.5 리듀싱
### 리듀싱 연산은 모든 스트림 요소를 처리해서 값으로 도출해야 한다.

`
int sum = numbers.stream().reduce(0, (a,b) -> a + b);
`
- 초깃값
- 두 요소를 조합해서 새로운 값을 만드는 binaryOp(), 예제에서는 람다 (a,b)-> a+b 사용

### 최대, 최소

reduce메서드의 인자에 스트림의 두 요소를 에서 최대값, 최소값을 반환하는 람다만 제공하면 전체 요소에서 최대, 최소값을 구할 수 있다. (스트림의 모든 요소를 소비할 때까지 해당 람다식 반복)

`  Optional<Integer> max = numbers.stream().reduce(Integer::max);`

### reduce 메서드의 장점과 병렬화
reduce는 내부 반복이 추상화되면서 내부 구현에서 병렬로 reduce 메서드를 실행할 수 있게된다. parallelStream()을 사용해서 모든 스트림 요소를 병렬적으로 처리할 수 있지만 자원의 비효율이 일어날 수 있으므로 사용하기에 적합한 상황인지를 확인해야함

### 스트림 연산에서의 stateless 개념
reduce, sum, max 등의 연산은 계산 결과를 누적해나갈 내부 상태가 필요하다. 하지만 아무리 요소 수가 많아도 현재까지의 합 처럼 참고가 필요한 내부 상태의 크기가 한정되어있다.



## 5.7 특화 스트림

### 숫자형 스트림

`
int calories = menu.stream()
				   .map(Dish::getCalories)
                                   .reduce(0, Integer::sum);
                                   
 `
 
 박싱 비용이 발생함, 

`int calories = menu.stream()
				   .map(Dish::getCalories)
                                   .sum();
                                   `
스트림 API 숫자 스트림을 효율적으로 처리하기 위하여 기본 특화 스트림을 제공한다.

- IntStream
- DoubleStream
- LongStream

### 숫자 스트림으로 맵핑

스트림을 특화 스트림으로 변환 시킬땐 mapToInt, mapToDouble, mapToLong을 가장 많이 사용함 map과 정확히 같은 기능을 수행하지만 특화 스트트림을 반환함


### 객체 스트림으로 복원하기

특화 스트림을 만들고 원 상태로 복원하는 코드

`IntStream intStream = menu.stream().mapToInt(Dish::getCalories);
Stream<Integer> stream = intStream.boxed();
 `
