### ISSUE TITLE
Chapter.6 스트림으로 데이터 수집

### ISSUE THREAD

**Issue by tmfrl1552** [FireInStove/modern-java-in-action#4]
## 👑 스터디장
슬기 ( @tmfrl1552  )

## 📖 스터디 범위
Chapter.6 스트림으로 데이터 수집

## 🕧 스터디 일정
24/01/04 (목) 09시

**Comment by flyingtw** [comment]
# 6 스트림으로 데이터 수집
## 6.1 컬렉터란 무엇인가?
- 명령형 프로그래밍에 비해 함수형 프로그래밍이 정말 편하다.
- 함수형 프로그래밍에서는 '무엇'을 원하는지 직접 명시 할 수 있다.
- 명령형 코드에서는 다중 루프와 조건문을 추가하며 가독성과 유지보수성이 크게 떨어진다.

### 6.1.1 고급 리듀싱 기능을 수행하는 컬렉터
- Collector 인터페이스의 메서드를 어떻게 구현하느냐에 따라 스트림에 어떤 리듀싱 연산을 수행할지 결정된다.

### 6.1.2 미리 정의된 컬렉터
- Collectors 클래스에서 제공하는 팩토리 메서드의 기능이 있다.
- 크게 3가지로 분류 할 수 있다.
-- 스트림 요소를 하나의 값으로 리듀스하고 요약
-- 요소 그룹화
-- 요소 분할

## 6.2 리듀싱과 요약
- 컬렉터로 스트림의 모든 항목을 하나의 결과로 합칠 수 있다.
- stream().collect(Collectors.counting())  => stream().count()

### 6.2.1 스트림값에서 최댓값과 최솟값 검색
- Comparator를 인수를 받아서 Collectors.maxBy로 최댓값을 찾는다.
- Optional 로 max 값이 없을 수 도 있다.
- 즉, 스트림에 있는 객체의 숫자 필드의 합계나 평균 등을 반환하는 연산에도 리듀싱 기능이 자주 사용된다.

### 6.2.2 요약 연산
- munu.stream().collect(averagingInt(Dish::getCalories)); 와 같이 객체의 특정 값의 평균 값 1개를 구할 수도 있다.
- summarizing 으로 요약할 수 도 있다.

### 6.2.3 문자열 연결
- .collect(joining()); 은 예를들어 문자열을 합쳐서 하나의 문자열로 만들 수 있다.

### 6.2.4 범용 리듀싱 요약 연산
- 여태까지 표현한 모든 컬랙터는 reducing 팩토리 메서드로도 정의할 수 있다. 즉, 범용 collectors.reducing으로도 구현할 수 있다.
- 하지만 프로그래밍적으로 특화되어 편하기 때문에 특화 컬렉터를 사용한다.
- 같은 연산도 람다식으로 표현할 수 있다.

## 6.3 그룹화
- 하나의 type으로 분류 한다음 그걸 키로 새로운 Map 들로 그룹화 할 수 있다.
- 메서드 참조 대신 람다 표현식으로도 로직을 구현 할 수 있다.
- 분류 함수의 수준을 둬서 첫번째 수준, 두번째 수준으로 그룹화를 세분화 할 수 있다.
- 그룹화를 세분화 해서 컬렉터 결과를 다른 형식에 사용하거나 서브 그룹으로 나누거나.. 할 수 있다. 흠.

## 6.4 분할
- 분할 함수는 불리언을 반환한다.
- 맵의 키 형식은 Boolean 이다. 
- 결과적으로는 true 또는 false의 두개의 그룹으로 분류된다.
- 참, 거짓 두개의 요소를 모두 유지하고 있다는게 분할의 장점이다.
- 분할이란 곧 특수한 종류의 그룹화라고 할 수 있다. 

## 6.5 Collector 인터페이스
-  toList나 groupingBy등 Collector 인터페이스를 구현하는 여러가지 컬렉터들이 있었다.
- 직접 커스텀해서 만들 수 도 있다.
- T, A, R 을 직접 impl 받아 구현 해볼 수 있다.

**Comment by yougahee** [comment]
# 📖 6장. 스트림으로 데이터 수집

### Collector 사용 예시
```java
// 요리의 개수 
long howManyDishes = menu.stream().collect(Collectors.counting());

// 최댓값, 최솟값
Comparator<Dish> dishCaloriesComparator = Comparator.comparingInt(Dish::getCalories);

Optional<Dish> mostCalorieDish = menu.stream.collect(maxBy(dishCaloriesComparator));

```

#### 요약 연산
- summingInt / summingDouble
- averagingInt
- maxBy
- summarizingInt : 위의 모든 요약 연산이 전부 다 있음
	- return : IntSummaryStatistics


#### 문자열 연결
- joining
```java
var shortMenu = menu.steam().map(Dish::getName).collect(joining(", "));
```

#### 범용 리듀싱 요약 연산
- 구현하는 방법은 다양하지만, 가독성을 고려하여 읽기 쉬운 방법으로 코드를 작성하자.

```java
Optional<Dish> mostCalorieDish = menu.stream.collect(reducing(
	(d1, d2) -> d1.getCalories() > d2.getCalories ? d1 : d2
));
```



### 그룹화
- groupingBy 함수를 기준으로 스트림이 그룹화되므로 이를 분류 함수라고 부른다.
- 그룹화맵 형태로 반환

#### 그룹화된 요소 조작
- 유용한 기능 : 매핑 함수를 이용해 요소를 변환하는 작업 
```java
Map<Dish.Tpye, List<String>> dishNamesByType =
	menu.strea()
		.collect(groupingBy(Dish::getType, mapping(Dish::getName, toList())));
```

#### 2가지 이상의 기준을 적용하여 그룹화
- groupingBy 안에 groupingBy를 사용하여.

```java
Map<Dish.Tpye, Map<CaloricLevel, List<Dish>> dishNamesByType =
	menu.strea()
		.collect(groupingBy(Dish::getType, 
			groupingBy(dish -> {
				if(dish.getCalories() <= 400)
					return CaloricLevel.DIET;
				else if (dish.getCalories() <= 700)
					return CaloricLevel.NORMAL;
				else
					return CaloricLevel.FAT;

			})
		);
```

#### 서브그룹으로 데이터 수집
- 컬렉터 결과를 다른 형식에 적용하기
- collectingAndThen > 적용할 컬렉터와 변환 함수를 인수로 받아서, 다른 컬렉터를 반환한다.
	- 리듀싱 컬렉터는 절대 Optional.empty를 반환하지 않음.
```java
Map<Dish.Tpye, Dish> dishNamesByType =
	menu.strea()
		.collect(groupingBy(Dish::getType, 
			collectingAndThen(
				maxBy(comparingInt(Dish::getCalories)),
			Optional::get))); // 변환 함수
```


### 분할함수
- 불리언을 반환하므로 맵의 키 형식은 Boolean
- 즉, 최대 2개의 그룹으로 분류된다.

```java
Map<Boolean, List<Dish>> partitionedMenu =
	menu.stream().collect(partitioningBy(Dish::isVegetarian))
```

- 장점 : 참/거짓 두가지 요소의 스트림 리스트를 모두 유지한다는 것


## Collector Interface
리듀싱 연산을 어떻게 구현할지 제공하는 메서드 집합으로 구성

1) supplier 메서드 
새로운 결과 컨테이너 만들기

- 파라미터가 없는 함수

```java
public Supplier<List<T>> supplier() {
	return () -> new ArrayList<T>();
}
```


2) accumulator 메서드
결과 컨테이너에 요소 추가하기


```java
public BiConsumer<List<T>, T> accumulator() {
	return List::add;
}
```

3) finisher 메서드 
최종 변환값을 결과 컨테이너로 적용하기

```java
public Function<List<T>, List<T>> finisher() {
	return Function.identity();
}
```


4) combiner 메서드
두 결과 컨테이너 병합


```java
public BinaryOperator<List<T>> combiner() {
	return (list1, list2) -> {
		list1.addAll(list2);
		return list1;
	}
}
```

5) Characteristics 메서드
컬렉션의 연산을 정의하는 Characteristics 형식의 불변 집합을 반환한다.

**Comment by tmfrl1552** [comment]
# Chapter6. 스트림으로 데이터 수집
## 6.1 컬렉터란 무엇인가?
* collect 에서는 리듀싱 연산을 이용해 스트림의 각 요소를 방문하면서 컬렉터가 작업을 처리함.
	* 보통 함수를 요소로 변환할 때는 컬렉터를 적용하며 최종 결과를 저장하는 자료구조에 값을 누적.
* 6장 > 미리 정의된 컬렉터, 즉 groupingBy와 같이 Collectors 클래스에서 제공하는 팩토리 메서드 기능 설명
* Collectors에서 제공하는 메서드 기능 > 크게 3가지 구분
	* 스트림 요소를 하나의 값으로 리듀스하고 요약
	* 요소 그룹화
	* 요소 분할 

## 6.2 리듀싱과 요약
### 6.2.1 스트림의 최댓값 최솟값 검색
* count() 팩토리 메서드 > 개수 카운팅하는 메서드
``` java
long howManyDishes = menu.stream().count();
```

* Collectors.maxBy, Collectors.minBy > 스트림의 최댓값과 최솟값 계산하는 메서드
``` java
Optional<Dish> mostCalorieDish = 
	menu.stream()
		.collect(maxBy(Comparator.comparingInt(Dish::getCalories)));
```

* 요약 연산
	* 스트림에 있는 객체의 숫자 필드의 합계나 평균등을 반환하는 연산
	* 리듀싱 기능 자주 사용


### 6.2.2 요약 연산
* Collectors.summingInt > int 형식 데이터의 총 합계 연산하는 팩토리 메서드
	* Collectors.summingLong, Collectors.summingDouble > long, double 형식의 데이터 요약
``` java 
// 메뉴 리스트의 총 칼로리를 계산하는 메서드
int totalCalories = menu.stream().collect(summingInt(Dish::getCalories));
```

* 다양한 형식으로 이루어진 숫자 집합의 평균 계산
	* Collectors.averagingInt, Collectors.averagingLong, Collectors.averagingDouble
``` java
double avgCalories = 
	menu.stream().collect(averagingInt(Dish::getCalories));
```

* summarizingInt > 요소 수, 합계, 평균, 최대/최솟값 계산을 한번에 수행하는 메서드
	* summarizingLong, summarizingDouble > LongSummarayStatistics, DoubleSummarayStatistics 존재
``` java
IntSummaryStatistics menuStatistics = 
	menu.stream().collect(summarizingInt(Dish::getCalories));

// menuStatistics 객체 출력 시
IntSummarayStatistics{count=9, sum=4300, min=120,
					  average=477.777778, max=800}
```


### 6.2.3 문자열 연결
* 컬렉터에 joining 팩토리 메서드 
	* 스트림의 각 객체에 toString 메서드를 호출해서 추출한 모든 문자열을 
	  '하나의 문자열로 연결해서 반환'한다.

``` java
String shortMenu = menu.stream().map(Dish::getName).collect(joining());

// Dish 클래스가 요리명을 반환하는 toString 메서드 포함시 map 생략 가능
String shortMenu = menu.stream.collect(joining());

// 두 요소 사이에 구분 문자열을 넣을 수 있도록 오버로드 된 joining 팩토리 메서드
String shortMenu = menu.stream().map(Dish::getName).collect(joining(", "));
```

### 6.2.4 범용 리듀싱 요약 연산
* Collectors.reducing > 이전에 살펴본 모든 컬렉터는 해당 메서드로 구현 가능
	* 프로그래밍적 편의성 때문에 특화된 컬렉터 사용(가독성도 중요)
* reducing 함수 > 3개 인수, 1개 인수
	* 3개 인수
		* 첫번째 인수 : 리듀싱 연산의 시작값 or 스트림에 인수가 없을 때 반환값
		* 두번째 인수 : 변환 함수 (ex. 요리를 칼로리 정수로 변환)
		* 세번째 인수 : 두 항목을 하나의 값으로 연산하는 BinaryOperator
	* 1개 인수
		* 스트림의 첫번째 요소를 첫번째 이수로 받음
		* 자신을 그대로 반환하는 항등함수를 두번째 인수로 받는 상황
		* 빈 스트림일 경우 시작값 설정되지 않을 수 있으므로 > Optional 객체 반환


#### 컬렉션 프레임워크의 유연성 : 같은 연산도 다양한 방식으로 수행 가능
``` java
int totalCalories = menu.stream().collet(reducing(0, // 초깃값
							 Dish::getCalories, // 변환 함수
							 Integer::sum)); // 합계 함수

// 요리 스트림이 비어있지 않다는 전제 하에 get 사용
int totalCalories = menu.stream.map(Dish::getCalories).reduce(Integer::sum).get;

// 스트림을 IntStream으로 맵핑한 후 sum 호출
int totalCalories = menu.stream.mapToInt(Dish::getCalories).sum();							 
```

#### 자신의 상황에 맞는 최적의 해법 선택
* 스트림 인터페이스에서 직접 제공하는 메서드를 이용하는 것에 비해, 컬렉터를 이용하는 코드가 더 복잡 함
	* 코드가 더 복잡한 대신, '재사용성'과 '커스터마이징 가능성'을 제공하는 높은 수준의 추상화과 일반화 제공
* 문제 해결할 수 있는 다양한 해결 방법 확인 후, 특화된 해결책을 고르는 것이 바람직.



## 6.3 그룹화
* Collectors.groupingBy > 그룹화 팩토리 메서드
	* 이 함수를 기준으로 Stream이 그룹화 되므로 > '분류 함수'라고 부름 
	* 그룹화 함수가 반환하는 키, 각 키에 대응하는 스트림의 모든 항목 리스트값 반환하는 맵 반환
``` java
Map<Dish.Type, List<Dish>> dishedByType = 
	menu.stream().collect(groupingBy(Dish::getType));
```

### 6.3.1 그룹화된 요소 조작
* filtering 메서드
	* Collectors 클래스의 또 다른 정적 팩토리 메서드로 프레디케이트를 인수로 받음
	* 프레디케이트로 각 그룹의 요소와 필터링 된 요소 재그룹화
``` java
Map<Dish.Type, List<Dish>> caloriesDishesByType =
	menu.stream()
		.collect(groupingBy(Dish::getType,
				 filtering(dish -> dish.getCalories() > 500, toList())));
```

* mapping 메서드 > 요소 변환해주는 메서드
``` java
Map<Dish.Type, List<Dish>> dishNamesByType = 
	menu.stream()
		.collect(groupingBy(Dish::getType, mapping(Dish::getName, toList())));
```

* flapMapping > 일반 맵이 아닌 flatMap 변환 수행
``` java
Map<Dish.Type, Set<String>> dishNamesByType = 
	menu.stream()
		.collect(groupingBy(Dish::getType,
				 flatMapping(dish -> dishTags.get(dish.getName()).stream(), toSet())));
```


### 6.3.2 다수준 그룹화
* 두 인수를 받는 팩토리 메서드 Collectors.groupingBy 를 이용해서 항목을 다수준으로 그룹화 가능
* Collectors.groupingBy 는 일반적인 분류 함수와 컬렉터를 인수로 받음
* n수준 그룹화의 결과는 n 수준 트리 구조로 표현되는 'n 수준 맵'이 됨


### 6.3.3 서브 그룹으로 데이터 수집
* collectingAndThen은 적용할 컬렉터와 변환 함수를 인수로 받아 다른 컬렉터를 반환
	* 반환되는 컬렉터는 기존 컬렉터의 래퍼 역할, collect의 마지막 과정에서 변환함수로 자신이 반환하는 값을 매핑
``` java
Map<Dish.Type, Dish> mostCaloricByType =
	menu.stream()
		.collect(groupingBy(Dish::getType, // 분류 함수
				 collectingAndThen(
				 	maxBy(comparingInt(Dish::getCalories)), // 감싸인 컬렉터
				 Optional::get))); // 변환 함수
```

* 일반적으로 스트림에서 같은 그룹으로 분류된 모든 요소에 리듀싱 작업을 수행할 때는
  팩토리 메서드 groupingBy에 두번째 인수로 전달한 컬렉터를 사용한다.
  * mapping메서드 자주 사용 됨.


## 6.4 분할
* 분할 이란?
	* 분할 함수(partitioning function)라 불리는 프레디케이트를 분류 함수로 사용하는 특수한 그룹화 기능
	* 불리언을 반환하므로 맵의 키 형식은 Boolean
	* 최대 두개의 그룹으로 분류(참 or 거짓의 값 가짐)
``` java
// 채식 요리와 채식이 아닌 요리로 분류
Map<Boolean, List<Dish>> partitionedMenu = 
	mnu.stream().collect(partitioningBy(Dish::isVegiterian));
```

### 6.4.1 분할의 장점
* 분할 함수가 반환하는 참, 거짓 두 가지 요소의 스트림 리스트를 모두 유지 > 분할의 장점
* 컬렉터를 두 번째 인수로 전달할 수 있는 오버로드된 버전의 partitioningBy 메서드 존재
	* ==> 원하는 형식의 결과값을 얻을 수 있음



## 6.5 Collector 인터페이스
* Collector 인터페이스는 리듀싱 연산(즉, 컬렉터)을 어떻게 구현할지 제공하는 메서드 집합으로 구성
``` java
//Collector 인터페이스의 시그니처와 다섯 개의 메서드 정의
public interface Collector<T, A, R> {
	Supplier<A> supplier();
	BiConsumer<A, T> accumulator();
	Function<A, R> finisher();
	BinaryOperator<A> combiner();
	Set<Characteristics> characteristics();
}
```
* T는 수집될 스트림 항목의 제네릭 형식
* A는 '누적자', 즉 수집 과정에서 중간 결과를 누적하는 객체의 형식
* R은 '수집 연산 결과 객체'의 형식(항상 그런 것은 아니지만 대개 컬렉션 형식)


### 6.5.1 Collector 인터페이스의 메서드 살펴보기
#### supplier 메서드: 새로운 결과 컨테이너 만들기
* supplier 메서드
	* 빈 결과로 이루어진 Supplier 반환
	* 수집 과정에서 빈 누적자 인스턴스를 만드는 파라미터가 없는 함수
``` java
public Supplier<List<T>> supplier(){
	return () -> new ArrayList<T>(); // ArraysList:new;
}
```

#### accumulator 메서드: 결과 컨테이너에 요소 추가하기
* accumulator 메서드
	* 리듀싱 연산을 수행하는 함수 반환
	* 스트림에서 n번째 요소를 탐색할때 두 인수, 즉 누적자(스트림의 첫 n-1개 항목을 수집한 상태)와
	  n번째 요소를 함수에 적용한다.
	* 함수의 반환값은 void > 요소를 탐색하면서 적용하는 함수에 의해 누적자 내부 상태가 바뀌므로
	                     누적자가 어떤 값일지 단정할 수 없음.


#### finisher 메서드: 최종 변환값을 결과 컨테이너로 적용하기
* finisher 메서드
	* 스트림 탐색을 끝내고 누적자 객체를 최종 결괄 변환하면서 누적 과정을 끝낼 떄 호출할 함수 반환
	* 누적자 객체가 이미 최종 결과인 상황에선 > 변환 과정이 필요하지 않으므로 항등 함수 반환

![순차 리듀싱 과정](https://github.com/FireInStove/modern-java-in-action/assets/52412936/637ebfb2-8e16-4738-8249-7de5dd732ec8)
* 실제로는 collect가 동작하기 전에 다른 중간연산과 파이프라인을 구성할 수 있게 해주는
  게으른 특성 그리고 병렬 실행 등도 고려해야 하므로 스트림 리듀싱 기능 구현은 생각보다 복잡


#### combiner 메서드: 두 결과 컨테이너 병합
* combiner 메서드
	* 스트림의 서로 다른 서브파트를 병렬로 처리할 때 누적자가 이 결과를 어떻게 처리할지 정의
	* 스트림의 리듀싱을 병렬로 수행 가능
		* 자바 7의 포크/조인 프레임워크와 Spliterator 사용


#### Characteristics 메서드
* characteristics 메서드
	* 컬렉터의 연산을 정의하는 Characteristics 형식의 불변 집합을 반환
	(컬렉터가 수행하는 작업의 속성에 대한 정보를 제공)
	* 스트림을 병렬로 리듀스 할 것인지 그리고 병렬로 리듀스 한다면 어떤 최적화를 선택해야 할지 힌트 제공
	* 다음 세 항목을 포함하는 열거 형
		* UNORDERED
			* 리듀싱 결과는 스트림 요소의 방문 순서나 누적 순서에 영향을 받지 않음
		* CONCURRENT
			* 다중 스레드에서 accumulator 함수를 동시에 호출, 컬렉터는 스트림의 병렬 리듀싱 수행 가능
		* IDENTITY_FINISH
			* finisher 메서드가 반환하는 함수는 단순히 identity를 적용할 뿐 이므로 이를 생략 가능
			* 리듀싱 과정의 최종 결과로 누적자 객체 바로 사용 가능
			* 누적자 A -> R로 안전하게 형변환

**Comment by kyueun** [comment]
## 컬렉터
### 고급 리듀싱 기능 수행하는 컬렉터
- 리듀싱 연산을 이용해 스트림의 각 요소를 방문하면서 컬렉터가 작업을 처리
- Collector 인터페이스의 메서드를 어떻게 구현하느냐에 따라 스트림이 어떤 리듀싱 연산을 수행할지 결정

### 미리 정의된 컬렉터
Collectors 클래스에서 제공하는 팩토리 메서드 ex. `groupingBy`
1. 스트림 요소를 하나의 값으로 리듀스하고 요약
    - 리스트에서 총합을 찾는 등 계산 수행
2. 요소 그룹화
    - 다수준으로 그룹화, 각각의 결과 서브그룹에 추가로 리듀싱 연산을 적용할 수 있도록 조합
3. 요소 분할
    - 한 개의 인수를 받아 불리언을 반환 -> 프레디케이트를 그룹화 함수로 사용

## 리듀싱과 요약
스트림의 모든 항목을 하나의 결과로 합칠 수 있음
1. 최댓값, 최솟값 검색
    - Comparator 구현 후, `Collectors.maxBy` 로 전달
2. 요약
    - 스트림에 있는 객체의 합계, 평균 등을 반환
3. 문자열 연결
    - `joining` 팩토리 메서드를 이용하면 각 객체에 toString 호출 후 추출한 문자열을 연결
4. 범용 리듀싱 요약
    - `reducing` 팩토리 메서드로 정의
    - ex
        ```java
            int totalCalories = menu.stream()
                .collect(
                    reducing(
                        0,  // 연산의 시작값, 스트림에 인수가 없는 경우 반환값
                        Dish::getCalories, // 스트림 요소를 원하는 형태로 변환할 때 사용하는 함수
                        (i,j) -> i+j // 같은 종류의 두 값을 통해 하나의 값 도출, BinaryOperator
                    )
                );
        ```

## 그룹화
데이터 집합을 하나 이상의 특성으로 분류해서 그룹화
1. 그룹화된 요소 조작
    - 목록이 비어있는 항목도 제외되지 않게 할 수 있음
    - 각 그룹의 요소를 변환
        - ex
            ```java
                Map<Type, List<String>> dishNamesByType = menu.stream()
                    .collect(
                        groupingBy(
                            Dish::getType,
                            mapping(Dish::getName, toList())
                        )
                    );
            ```
2. 다수준 그룹화
    - ex
        ```java
            Map<Type, Map<CaloricLevel, List<Dish>>> map = menu.stream()
                .collect(
                    groupingBy(
                        Dish::getType,
                        groupingBy(dish -> {
                            if (dish.getCalories()<=400) return DIET;
                            else if (dish.getCalories()<=700) return NORMAL;
                            else return FAT;
                        })
                    )
                );
        ```
3. 서브그룹으로 데이터 수집
    - ex
        ```java
            Map<Type, Set<CalricLevel>> map = menu.stream()
                .collect(
                    groupingBy(
                        Dish::getType,
                        mapping(
                            dish -> {
                                if (dish.getCalories()<=400) return DIET;
                                else if (dish.getCalories()<=700) return NORMAL;
                                else return FAT;
                            },
                            toCollection(HashSet::new)
                        )
                    )
                );
        ```

## 분할
프레디케이트를 분류 함수로 사용
- ex
    ```java
        Map<Boolean, List<Dish>> partitionedMenu = menu.stream()
            .collect(partitioningBy(Dish::isVegetarian));
    ```

장점
- 참, 거짓 두 가지 요소의 스트림 리스트를 모두 유지

## Collector 인터페이스
리듀싱 연산(컬렉터)을 어떻게 구현할지 제공하는 메서드 집합으로 구성
```java
    /*
        T : 수집될 스트림 항목의 제네릭 형식
        A : 누적자, 수집 과정에서 중간 결과를 누적하는 객체의 형식
        R : 수집 연산 결과 객체의 형식
    */
    public interface Collector<T, A, R> {
        Supplier<A> supplier();
        BiConsumer<A, T> accumulator();
        Function<A, R> finisher();
        BinaryOperator<A> combiner();
        Set<Characteristics> characteristics();
    }
```
- `supplier()`
    - 새로운 결과 컨테이너 만들기
    - 빈 결과로 이루어진 Supplier 반환
    - 수집 과정에서 빈 누적자 인스턴스를 만드는 파라미터가 없는 함수
- `accumulator()`
    - 결과 컨테이너에 요소 추가하기
    - 리듀싱 연산을 수행하는 함수 반환
    - n번째 요소 탐색 시, n-1까지 수집한 누적자와 n번째 요소를 함수에 적용
    - 함수에 의해 누적자 내부 상태가 바뀌므로 누적자가 어떤 값인지 단정할 수 없음
- `finisher()`
    - 최종 변환값을 결과 컨테이너로 적용하기
    - 스트림 탐색을 끝내고 누적자 객체를 최종 결과로 변환하면서 누적 과정을 끝낼 때 호출할 함수 반환
- `combiner()`
    - 두 결과 컨테이너 병합
    - 스트림의 서로 다른 서브파트를 병렬로 처리할 때 누적자가 이 결과를 어떻게 처리할지 정의
    - 스트림의 리듀싱을 병렬로 수행 가능
- `characteristics()`
    - 컬렉터의 연산을 정의하는 Characteristics 형식의 불변 집합을 반환
    - 스트림을 병렬로 리듀스할 것인지, 병렬로 한다면 어떤 최적화를 선택해야 할지 힌트 제공
    - 열거형
        - UNORDERED: 리듀싱 결과는 스트림 요소의 방문 순서, 누적 순서에 영향을 받지 않음
        - CONCURRENT: 다중 스레드에서 accumulator를 동시에 호출할 수 있으며, 이 컬렉터는 스트림의 병렬 리듀싱을 수행 가능
        - IDENTITY_FINISH: finisher 메소드가 반환하는 함수는 단순 identity를 적용, 생략 가능 -> 리듀싱 최종 결과로 누적자 객체를 바로 사용 가능
